### ISSUE TITLE
Install instructions failing

### ISSUE THREAD

**Issue by jstac** [executablebooks/MyST-Parser#122]
Thought I'd trying building the docs but the pandas theme is still causing me grief.  Other instructions are also generating errors.

Following install instructions [here](https://github.com/ExecutableBookProject/MyST-Parser) in a fresh conda environment (`conda create --name test1 sphinx`) I get

![Screenshot_2020-03-20_17-14-03](https://user-images.githubusercontent.com/3887684/77140611-3ef0d800-6ace-11ea-82c2-3269a2cde5d0.png)

(This follows `conda install -c conda-forge myst-parser`)

Running `pip install git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master` and then repeating leads to exactly the same error.

With `pip install myst-parser[sphinx]` I get

![Screenshot_2020-03-20_17-17-08](https://user-images.githubusercontent.com/3887684/77140749-b45ca880-6ace-11ea-950f-c9e853594cfe.png)

With the last set of developer instructions I get

![Screenshot_2020-03-20_17-07-43](https://user-images.githubusercontent.com/3887684/77140400-95a9e200-6acd-11ea-879d-6f8169cd65ee.png)

**Comment by chrisjsewell** [comment]
Your literally a day too early, see #121 where the newly released theme is being incorporated.

**Comment by chrisjsewell** [comment]
Regarding the pip install, maybe it’s you dodgy zsh terminal, because I don’t see any reason for the not found error. Have you tried doing this with any other packages? `pip install any-package[some-extra]`

**Comment by chrisjsewell** [comment]
What version of pip are you using? does it ‘understand’ extras, it seems that it’s seeing it as part of the package name

**Comment by jstac** [comment]
It's a fresh conda environment so the latest version of pip (20.0.2).  But yeah, looks like you're right about zsh: https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity

**Comment by chrisjsewell** [comment]
closing as I believe this is fixed now
