### ISSUE TITLE
Add renderer for markdown-it-py amsmath extension

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#132]
See executablebooks/markdown-it-py#12 and executablebooks/MyST-NB#126.

- Make the extension optional (off by default?)
- Parse `label`/`tag` in latex? (multiple labels in split environments?)

**Comment by phaustin** [comment]
as far as prior-art goes -- here's the [relevant piece of bookdown code](https://github.com/rstudio/bookdown/blob/cd97d40eccd2ce8d05e39b7815ede59f7b3aa4d6/R/html.R#L1063-L1088).  Pretty basic, they just post-process the pandoc-produced html and use regexps to rewrite the labels.
