### ISSUE TITLE
Add github links to our docs

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#135]
The homepage of our documentation doesn't have any github links or badges (or non-github badges for that matter)...we should add some!

**Comment by asmeurer** [comment]
Indeed, the "contributing" page has a bunch of instructions, but doesn't even link to the repo!

**Comment by choldgraf** [comment]
I partially addressed this here: https://github.com/executablebooks/MyST-Parser/pull/138

though we can / should probably include more links to the github repo in there
