### ISSUE TITLE
Use a different example than wealth dynamics

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#136]
The [wealth dynamics example](https://myst-parser.readthedocs.io/en/latest/examples/wealth_dynamics_md.html) is awesome content, but it shows off functionality that is not in myst-parser (in this case, a bunch of Jupytext syntax and also `{code-cell}` directives, which as already led to some confusion (#133). I propose that we find a new example that purely uses MyST instead of also using MyST-NB syntax.

**Comment by rossbar** [comment]
FWIW I have a branch of the open textbook [Elegant Scipy](https://github.com/rossbar/elegant-scipy/tree/myst) where I've converted the 8 chapters from the original markdown+custom extensions syntax into MyST. This may be relevant as I *only* made changes to test the MyST-parser, not the other features from `MyST-NB` etc. The chapters are pure "MyST-flavored" markdown files and can be converted to html via sphinx using only the `myst_parser` extension.

If this is of interest I'd be happy to help incorporate a piece (perhaps a single chapter?) into the docs here. Let me know!

**Comment by choldgraf** [comment]
Go for it!

**Comment by chrisjsewell** [comment]
This example was removd a long time ago
