### ISSUE TITLE
Jupyter widget tokens don't have a renderer

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#137]
If we use MyST-NB to build a notebook that has a `{code-cell}` that produces a widget, then it raises a myst-parser error:

```
..../myst-parser/myst_parser/docutils_renderer.py in render(self, tokens, options, env)
    107                 self.current_node.append(
    108                     self.reporter.warning(
--> 109                         f"No render method for: {token.type}", line=token.map[0]
    110                     )
    111                 )

TypeError: 'NoneType' object is not subscriptable
```

looking at the myst-parser, it looks like it is erroring because the Token it tries to render is of type `Token(type='jupyter_widget_state',` and there is no renderer for this type, but instead of throwing the error message it chokes because it tries to get `token.map[0]` but `token.map` is `None`.

I'm not exactly sure what the problem here is, but wanted to flag it for future ref

**Comment by chrisjsewell** [comment]
I think this is old, because the renderer for these are implemented in myst-nb
