### ISSUE TITLE
Can't add targets to images?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#140]
I just tried adding an image with a `:target:` in MyST, and I got this sphinx error:

```
...jupyter-book/docs/content/content-blocks.md:37: WARNING: Directive 'image' cannot be mocked: MockingError: MockState has not yet implemented attribute 'parse_target'
```

Just want to confirm that this is because MyST-parser doesn't yet have the syntax to parse targets?

And as an aside - how would we recommend people include an image *with a link* that uses MyST markdown instead of `![]()` syntax?

**Comment by chrisjsewell** [comment]
The first thing to do is find where the `parse_target` method is implemented in the docutils (GitHub mirror) source code and link here

**Comment by choldgraf** [comment]
https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/parsers/rst/states.py#L1927 ?

**Comment by chrisjsewell** [comment]
Ta, so what we need to now do is implement this method on https://github.com/executablebooks/MyST-Parser/blob/f32bd380bdec755238566fa91352f9ed1d491036/myst_parser/mocking.py#L58

**Comment by choldgraf** [comment]
we want it to be the exact same method, right? There shouldn't be any difference between how myst parses this kind of thing from rST?

**Comment by chrisjsewell** [comment]
From a brief scan, there should be no difference. Although obviously we should add a test or two with the PR to clarify

**Comment by choldgraf** [comment]
See https://github.com/executablebooks/MyST-Parser/pull/141 for a fix (I think)
