### ISSUE TITLE
Possible to make internal links refs work with file extensions?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#143]
We've had a few users who have asked if it's possible to have their documents work *both* as standalone markdown files, and as built documentation w/ Jupyter Book. One place that this breaks down is relative links:

If you have a markdown file that is just rendered to HTML, then you generally structure your links to another page like: `[other page](myotherpage.md)`.

If you are building a sphinx site, it doesn't allow you (I think) to include the extension in the `{any}` link, you need to structure it like so: `[other page](myotherpage)`.

Is there any way that we can get support the `[other page](myotherpage.md)` use-case? Maybe I am missing a Sphinx setting somewhere that we just need to document?

**Comment by phaustin** [comment]
nbsphinx seems ok with suffixes?  https://github.com/spatialaudio/nbsphinx/blob/0.7.0/doc/subdir/a-notebook-in-a-subdir.ipynb

**Comment by choldgraf** [comment]
Hmm - I suspect it might be possible in `nbsphinx` because of https://github.com/spatialaudio/nbsphinx/blob/master/src/nbsphinx.py#L1534
