### ISSUE TITLE
Issue with list-table

### ISSUE THREAD

**Issue by asmeurer** [executablebooks/MyST-Parser#147]
I am trying to convert my site https://github.com/asmeurer/brown-water-python/pull/2 from recommonmark to Myst.

One issue I'm having so far is with a list-table. 

You can see how the table renders with recommonmark [here](https://www.asmeurer.com/brown-water-python/alternatives.html#summary), which is how I like it.  Myst renders it like [this](https://www.asmeurer.com/brown-water-python/docs-myst/alternatives.html#summary).

You can see how I modified it for Myst here https://github.com/asmeurer/brown-water-python/pull/2/commits/1395106a8c80ae615d70cafdeef7e8c5abe1f6fc.

There are two problems

- The table proportions are off. It decided to make the left and right columns small and the middle column wide, instead of equally wide.
- The rst link in the last row doesn't work.

**Comment by chrisjsewell** [comment]
> The rst link in the last row doesn't work.

That's because it should be written in Markdown. Another that should be stressed in the documentation, is that all "nested" content in directives will be parsed as markdown, not rST.
i.e. `` `garbage in, garbage out <https://en.wikipedia.org/wiki/Garbage_in,_garbage_out>`_``, should be `[garbage in, garbage out](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out)`. This is IMO the major advantage over recommonmark; no switching between rST and Markdown.

**Comment by chrisjsewell** [comment]
<details>
<summary>MyST</summary>
<table class="docutils align-default">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Regular expressions</p></th>
<th class="head"><p><code class="docutils literal notranslate"><span class="pre">tokenize</span></code></p></th>
<th class="head"><p><code class="docutils literal notranslate"><span class="pre">ast</span></code></p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>Can work with incomplete or invalid Python.</p></td>
<td><p>Can work with incomplete or invalid Python, though you may need to
watch for <code class="docutils literal notranslate"><span class="pre">ERRORTOKEN</span></code> and exceptions.</p></td>
<td><p>Requires syntactically valid Python (with a few minor exceptions).</p></td>
</tr>
<tr class="row-odd"><td><p>Regular expressions can be difficult to write correctly and maintain.</p></td>
<td><p>Token types are easy to detect. Larger patterns must be amalgamated
from the tokens. Some tokens mean different things in different contexts.</p></td>
<td><p>AST has high-level abstractions such as <code class="docutils literal notranslate"><span class="pre">ast.walk</span></code> and
<code class="docutils literal notranslate"><span class="pre">NodeTransformer</span></code> that make visiting and transforming nodes easy,
even in complicated ways.</p></td>
</tr>
<tr class="row-even"><td><p>Regular expressions work directly on the source code, so it is trivial
to do lossless source code transformations with them.</p></td>
<td><p>Lossless source code transformations are possible with <code class="docutils literal notranslate"><span class="pre">tokenize</span></code>, as all the
whitespace can be inferred from the <code class="docutils literal notranslate"><span class="pre">TokenInfo</span></code> tuples. However, it can
often be tricky to do in practice, as it requires manually accounting
for column offsets.</p></td>
<td><p>Lossless source code transformations are impossible with <code class="docutils literal notranslate"><span class="pre">ast</span></code>, as it completely
drops whitespace, redundant parentheses, and comments (among other
things).</p></td>
</tr>
<tr class="row-odd"><td><p>Impossible to detect edge cases in all circumstances, such as code that
actually is inside of a string.</p></td>
<td><p>Edge cases can be avoided. Differentiates between actual code and code
inside a comment or string. Can still be fooled by invalid Python (though this can
often be considered a <code class="docutils literal notranslate"><span class="pre">garbage</span> <span class="pre">in,</span> <span class="pre">garbage</span> <span class="pre">out</span> <span class="pre">&lt;https://en.wikipedia.org/wiki/Garbage_in,_garbage_out&gt;</span></code>_ scenario).</p></td>
<td><p>Edge cases can be avoided effortlessly, as only valid Python can even
be parsed, and each node class represents that syntactic construct
exactly.</p></td>
</tr>
</tbody>
</table>
</details>

<details>
<summary>Recommonmark</summary>
<table class="docutils align-default">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Regular expressions</p></th>
<th class="head"><p><code class="docutils literal notranslate"><span class="pre">tokenize</span></code></p></th>
<th class="head"><p><code class="docutils literal notranslate"><span class="pre">ast</span></code></p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>Can work with incomplete or invalid Python.</p></td>
<td><p>Can work with incomplete or invalid Python, though you may need to
watch for <code class="docutils literal notranslate"><span class="pre">ERRORTOKEN</span></code> and exceptions.</p></td>
<td><p>Requires syntactically valid Python (with a few minor exceptions).</p></td>
</tr>
<tr class="row-odd"><td><p>Regular expressions can be difficult to write correctly and maintain.</p></td>
<td><p>Token types are easy to detect. Larger patterns must be amalgamated
from the tokens. Some tokens mean different things in different contexts.</p></td>
<td><p>AST has high-level abstractions such as <code class="docutils literal notranslate"><span class="pre">ast.walk</span></code> and
<code class="docutils literal notranslate"><span class="pre">NodeTransformer</span></code> that make visiting and transforming nodes easy,
even in complicated ways.</p></td>
</tr>
<tr class="row-even"><td><p>Regular expressions work directly on the source code, so it is trivial
to do lossless source code transformations with them.</p></td>
<td><p>Lossless source code transformations are possible with <code class="docutils literal notranslate"><span class="pre">tokenize</span></code>, as all the
whitespace can be inferred from the <code class="docutils literal notranslate"><span class="pre">TokenInfo</span></code> tuples. However, it can
often be tricky to do in practice, as it requires manually accounting
for column offsets.</p></td>
<td><p>Lossless source code transformations are impossible with <code class="docutils literal notranslate"><span class="pre">ast</span></code>, as it completely
drops whitespace, redundant parentheses, and comments (among other
things).</p></td>
</tr>
<tr class="row-odd"><td><p>Impossible to detect edge cases in all circumstances, such as code that
actually is inside of a string.</p></td>
<td><p>Edge cases can be avoided. Differentiates between actual code and code
inside a comment or string. Can still be fooled by invalid Python (though this can
often be considered a <a class="reference external" href="https://en.wikipedia.org/wiki/Garbage_in,_garbage_out">garbage in, garbage out</a> scenario).</p></td>
<td><p>Edge cases can be avoided effortlessly, as only valid Python can even
be parsed, and each node class represents that syntactic construct
exactly.</p></td>
</tr>
</tbody>
</table>
</details>

**Comment by asmeurer** [comment]
Ah gotcha, the code from the invalid link was messing up the table width.

**Comment by chrisjsewell** [comment]
I believe this is now fixed
