### ISSUE TITLE
Nested markup in link not working with cross-reference

### ISSUE THREAD

**Issue by asmeurer** [executablebooks/MyST-Parser#148]
If I have a link like 

```
[`page`](something.html#reference)
```

The nested markup in `page` works fine. But if I instead use `reference` as a cross-reference like

```
[`page`](reference)
```

The `page` part isn't rendered with the nested markup.

**Comment by chrisjsewell** [comment]
> The page part isn't rendered with the nested markup.

As in it shows as `` `page` `` instead of `page`?

**Comment by asmeurer** [comment]
Here is what I mean. The link to `ENCODING` should look like it does [here](https://www.asmeurer.com/brown-water-python/docs-myst/helper-functions.html#untokenize-iterable), but it is rendering like [this](https://www.asmeurer.com/brown-water-python/docs-myst/helper-functions.html#untokenize-iterable).

Here is the code https://github.com/asmeurer/brown-water-python/pull/2/commits/c7c62d46ed988c90383ee1a041c1ea747c52100f#diff-34534a52d2a004b4add6ed5bc4cf09f3R10

**Comment by chrisjsewell** [comment]
> Here is what I mean. The link to ENCODING should look like it does here, but it is rendering like this.

These links are the same lol

**Comment by asmeurer** [comment]
Copy-paste error. It should be fixed now.

**Comment by choldgraf** [comment]
So the problem is that "encoding" should have a `pre` tag, but in the myst-parser version it does not (it has a `std std-ref` tag).

So, it should be `ENCODING`, and instead it is rendered as ENCODING.
