### ISSUE TITLE
Add support for defintion lists

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#153]
Basically implement https://github.com/markdown-it/markdown-it-deflist in markdown-it-py then allow the extension to be (optionally?) loaded in https://github.com/executablebooks/MyST-Parser/blob/8dda2f73364853cb572a50c53434c385db266d7c/myst_parser/sphinx_parser.py#L196

**Comment by dhermes** [comment]
@chrisjsewell Per our discussion on #163, here is an example of a directive I'm drafting for a Go method:

````
```{go:method} ApplyMigration
:file: manager.go
:line-number: 137
:receiver: *Manager
:param-name 0: ctx
:param-type 0: context.Context
:param-name 1: migration
:param-type 1: Migration
:return-name 0: err
:return-type 0: error

ApplyMigration creates a transaction that runs the "Up" migration.
```
````

(I'm open to other variants of the `param-*` / `return-*` approach. It just needs to be flexible enough to have named and unnamed values in a signature and the actual type can be quite complex. Also, unlike Python or other languages there is no Go convention (yet) for documenting individual parameters so this is strictly a mapping to name/type expression, in order.)

**Comment by pradyunsg** [comment]
Is this not resolved?

**Comment by chrisjsewell** [comment]
yep 👍 I would note though that what @dhermes above is after is a field list markodown-it plugin + render method, see https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#field-lists

so I'll close this one, but if you want to open a new issue about that, by all means go ahead (I thought there already was one, but apparently not)
