### ISSUE TITLE
Unknown ref on /index

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#158]
The builds have started failing with an error like so:

```
/home/circleci/project/docs/index.md:17: WARNING: unknown document: sphinx:intro
```

it comes from this line:

```
* **[A markdown parser for Sphinx](parse-with-sphinx)**. You can write your entire
  {doc}`Sphinx documentation <sphinx:intro>` in markdown.
```

`sphinx:intro` isn't defined anywhere so that's why it's failing. I'm not sure why this suddenly started happening

**Comment by chrisjsewell** [comment]
this is because it's an intersphinx reference to the `intro` page of the sphinx documentation, which has been changed recently to `usage/quickstart`
