### ISSUE TITLE
Add table directive to the docs

### ISSUE THREAD

**Issue by amueller** [executablebooks/MyST-Parser#160]
There seems to be a table directive to do two-column layouts.
I'm not sure if that's from markdown, but it's extensively used in the docs:
https://github.com/executablebooks/MyST-Parser/blob/master/docs/using/syntax.md

However, it's not explained in the docs from what I can see.
I basically wanted to create a table similar to the one here:
https://myst-parser.readthedocs.io/en/latest/using/syntax.html#directives-a-block-level-extension-point
and would have given up if it wasn't used in the docs and I could look at the source code ;)

**Comment by chrisjsewell** [comment]
They are https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table, which yes as you can see, I'm a big fan 😄 
As mentioned in #81 I will am developing https://github.com/executablebooks/sphinx-ext-autodoc to hopefully document all these directives.

**Comment by amueller** [comment]
Cool! It would be very helpful ;)

**Comment by chrisjsewell** [comment]
👍 I'll close this as a duplication of #81
