### ISSUE TITLE
Extend support for labels/captions to markdown-style images

### ISSUE THREAD

**Issue by rossbar** [executablebooks/MyST-Parser#161]
**Describe the solution you'd like**

Inclusion of images into documents is very common, and it is very easy to do so quickly with markdown syntax, i.e.

```
![some text](image_resource)
```

For scientific publishing, it is very common to want to caption images and reference them from the text. MyST provides the handy `{figure}` directive to accomplish this:

````
```{figure} image_resource
---
name: figure_label
---
my caption
```
````

It would be a nice enhancement if authors could create reference-able, captioned images using markdown syntax as well. It seems there might be a sensible way to add this feature by:
 1. Allowing references to markdown images via the `(target)=` link-creation syntax, and
 2. Interpreting the bracketed text as the caption text.

Thus

````
```{figure} image_resource
---
name: my_figlabel
---
my caption.
```
````

could equivalently be written as

```
(my_figlabel)=
![my caption.](image_resource)
```

**Describe alternatives you've considered**

The `{figure}` directive is entirely sufficient to cover the above use-case; this is just an idea for some syntactic sugar as I find the markdown syntax easier to remember.

**Additional context**

I didn't see any related open issues/enhancements from a quick search, but if I've missed something please feel free to close!

**Comment by chrisjsewell** [comment]
Certainly seems feasible. Would be interesting to see what the current behaviour of adding the target element above an image is, since it is meant to apply itself to the next element.

**Comment by rossbar** [comment]
> Would be interesting to see what the current behaviour of adding the target element above an image is, since it is meant to apply itself to the next element.

Using the myst_parser extension with sphinx (`myst-parser==0.8.1`) and the following input (e.g.):

```
... text block ...

(fig:dna)=                                                                      
![dna](https://upload.wikimedia.org/wikipedia/commons/e/e4/DNA_chemical_structure.svg)

... text block with {numref}`fig:dna` in it ...
```

currently, the only thing I see is an undefined label warning:

```
sphinx/content/ch1.md:84: WARNING: undefined label: fig:dna
```

**Comment by chrisjsewell** [comment]
Se https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#markdown-figures 😄
