### ISSUE TITLE
Add an `eval_rst` directive

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#164]
In https://github.com/executablebooks/MyST-Parser/issues/163 we identified that there may be circumstances where the author still needs to write rST with MyST. For example, if a person uses `autodoc` and wants their documentation written in MyST, but has docstrings written in rST.

In that case, we could include a directive like `recommonmark`'s `eval_rst` that will call the rST parser on its content.

Another possible approach (maybe this is unrealistic?) is to allow for a flag in *all* directives used by MyST-parser that could tell the directive to parse the content with the rST parser instead of the MyST parser.

**Comment by chrisjsewell** [comment]
> Another possible approach (maybe this is unrealistic?) is to allow for a flag in all directives used by MyST-parser that could tell the directive to parse the content with the rST parser instead of the MyST parser.

From here https://github.com/executablebooks/MyST-Parser/issues/163#issuecomment-640150607, it looks like sphinx does some weird stuff with the `auto` directives, actually rewriting the directive in rST format before parsing. In this case that approach would not work.

**Comment by choldgraf** [comment]
Just a note that it looks like this is where recommonmark does this: https://github.com/readthedocs/recommonmark/blob/c4d575bd7bd5dd992cc3e2bed9dce625f4622a4d/recommonmark/transform.py#L246

It looks like they pass the contents to the RST state parser, which I _think_ we have access to in MyST? We're using a Markdown "mock" parser, so hopefully the rST parser is available as well

**Comment by asmeurer** [comment]
I was thinking, if it isn't hard, it might be useful to also provide the inverse directive, like `.. eval_markdown::` for RST. That way things that currently have to be written in RST like https://github.com/executablebooks/MyST-Parser/issues/163 can still include Markdown segments.
