### ISSUE TITLE
{ref}`link <target>` syntax doesn't work if broken with a newline

### ISSUE THREAD

**Issue by asmeurer** [executablebooks/MyST-Parser#169]
For example

```
{ref}`Name <target>`
```

works, but

```
{ref}`Name
<target>`
```

does not. It just produces 

```
{ref}Name <target>
```

in the resulting document.

This is annoying because I typically text wrap my Markdown in my editor to 80 characters, and this happens automatically on spaces. Virtually every other Markdown syntax works when broken along newlines, so this is presumably just an oversight.

**Comment by chrisjsewell** [comment]
Hey @asmeurer, well this is probably just more general to all roles: https://github.com/executablebooks/markdown-it-py/blob/c5be8d9af46f8e9484cacead123acfae25d89086/markdown_it/extensions/myst_role/index.py#L8

At least for now, what about just using?

```md
[Name
](target)
```

**Comment by asmeurer** [comment]
I think I was trying to use a more specific autodoc thing like `func` instead of `ref` so I had to use the `{ref}` syntax.

**Comment by chrisjsewell** [comment]
> I think I was trying to use a more specific autodoc thing like `func` instead of `ref` so I had to use the `{ref}` syntax.

`[Name](target)` *should* still work though if the target is a `func`, since it uses the [any role logic](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-any) to look through all referencable objects

**Comment by asmeurer** [comment]
I guess it does work for the example in my docs. In general though, you sometimes have to specify the type if there is an ambiguity with `any`.

**Comment by chrisjsewell** [comment]
> I guess it does work for the example in my docs. In general though, you sometimes have to specify the type if there is an ambiguity with `any`.

True

**Comment by webknjaz** [comment]
I've filed #448 (now closed) when I failed to find this issue. Just wanted to let you know that this is still broken. And yes, I also line-wrap text files for similar reasons. The use-case is pretty valid.

**Comment by chrisjsewell** [comment]
Heya, will be fixed with https://github.com/executablebooks/mdit-py-plugins/pull/32
