### ISSUE TITLE
Add substitution syntax(?)

### ISSUE THREAD

**Issue by SG-phimeca** [executablebooks/MyST-Parser#172]
Adding the following into `conf.py`

    rst_prolog = """
    .. |xyzzy| replace:: Nothing happens.
    """

allows to replace `|xyzzy|` by `Nothing happens.` in all ReST source files but not in Markdown files.
This would be a very useful feature, for instance for inline images, or simply to have a system for macros.

**Comment by choldgraf** [comment]
Here's the relevant bit from the rST docs:

https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#substitution-definitions

Also - just to clarify, `conf.py` is not integral to this issue, right?

**Comment by chrisjsewell** [comment]
Thanks @SG-phimeca, yes this syntax is not (currently) implemented in MyST (or in markdown).

It is a syntax that has come up before in discussion here: https://github.com/executablebooks/MyST-Parser/issues/31#issuecomment-592136776

**Comment by choldgraf** [comment]
I wonder if we could piggy-back on `LinkDefinition` for this?

E.g. support something like:

```
[key]: Any arbitrary text 
```

and then allow for `[key][]` in the text, and if that exists then assume the *content* should be replaced?

**Comment by chrisjsewell** [comment]
I'm very sceptical that this could be done in a way that didn't break commonmark compatibility 🤔

**Comment by choldgraf** [comment]
yeah I was worried about that too...looks like commonmark does already render the syntax I showed:

![image](https://user-images.githubusercontent.com/1839645/85430375-eb5eb200-b534-11ea-92d3-f843037dafbd.png)

**Comment by nickcrider** [comment]
+1 for the standard `rst_prolog` substitution syntax.

Our particular use-case [involves the rST substitution syntax in code-blocks](https://github.com/adamtheturtle/sphinx-substitution-extensions) to keep example code up-to-date. Unfortunately not having this syntax is blocking me from switching our documentation over to MyST.

However, playing around with it, I found if you do:
`````
```{eval-rst}

.. |sub| replace:: subbed

Test sub: |sub|
```
`````

Sphinx throws a `WARNING: Undefined substitution referenced: "sub"` so at least it seems like the plumbing is partially there.

**Comment by mgielda** [comment]
of course we'd also need a special sub directive to define the substitution, but I assume that would be doable, unless of course my rst fu is failing me and you cannot have a role and directive with the same name. (then we'd use another name?)

**Comment by AntonKrug** [comment]
Hi @mgielda what a surprise to find you here :)

https://jinja.palletsprojects.com/en/2.11.x/templates/#variables

You can wrap your whole document into the jinja directive with 'foo' argument and then in the body just use {{bar}}
I would include snippet here, but even the escaped Myst syntax is breaking this markdown.

**Comment by chrisjsewell** [comment]
See https://myst-parser--273.org.readthedocs.build/en/273/using/syntax-optional.html#substitutions, you can leave your thoughts at #273

**Comment by chrisjsewell** [comment]
Note substitutions and prologs are a little different, this issue is concerned with substitutions and #270 is specifically for prologs/epilogs
