### ISSUE TITLE
Move back to CircleCI(?)

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#177]
@choldgraf I've just realised an issue here: so with the circleci the documentation was running with the flags: https://github.com/executablebooks/MyST-Parser/blob/ba5c56c391ced762d617c254e93db5e2c808cb1d/docs/Makefile#L23-L24

which means that it runs in "nitpick" mode `-n`, fails on warnings `-W`, but still tries to continue building the documentation even if there is a failure `--keep-going`.
This ensures that the CI fails on warnings, like missing references, but if won't stop at the first warning, so that you can see all the warnings in one run and also view the final documentation.

With this new CI, it currently won't fail on warnings.
You can add https://docs.readthedocs.io/en/latest/config-file/v2.html#sphinx-fail-on-warning, which I guess is equivalent to `-nW`, but there appears to be no option for `--keep-going`, and thus makes it tedious to not be able to identify all warnings in one run.

_Originally posted by @chrisjsewell in https://github.com/executablebooks/MyST-Parser/pull/175#issuecomment-650079264_

**Comment by chrisjsewell** [comment]
if we didn't want to go back to circle-ci, then we should add a job in the github actions to run the build + keep RTD for the previews

**Comment by choldgraf** [comment]
That's a good point - I think we should just use a GHA for this, and build our docs at the same time we run our tests. The only reason that we were using CircleCI was because it has artifact previewing, so no reason to need to use it if we have previewing via readthedocs. That work?

**Comment by choldgraf** [comment]
I also opened up https://github.com/readthedocs/readthedocs.org/issues/7240 to suggest that RTD add this feature, or something like it

**Comment by chrisjsewell** [comment]
Yep sounds good to me 👍
Can’t remember if you have made this change in any of the other repos yet; but obviously we also want to apply this in those as well

**Comment by choldgraf** [comment]
I think we've done it for a couple, will try to start adding this back in here and there

**Comment by chrisjsewell** [comment]
Cheers

**Comment by choldgraf** [comment]
ah actually it looks like we could do nitpicky with RTD if we wanted:

https://github.com/readthedocs/readthedocs.org/issues/7240#issuecomment-650352249

do you think that's enough? Or still worth using GHA?

**Comment by chrisjsewell** [comment]
that wasn't the issue: see https://github.com/readthedocs/readthedocs.org/issues/7240#issuecomment-650374579

**Comment by choldgraf** [comment]
makes sense - I'm happy with keeping this on GHA if that doesn't pan out on RTD
