### ISSUE TITLE
Sphinx 3 support

### ISSUE THREAD

**Issue by asmeurer** [executablebooks/MyST-Parser#183]
I noticed that MyST pins sphinx <3. I didn't see any issues about Sphinx 3 support. Is this something that will be difficult to add? There are some new features of Sphinx that are only available in the newest versions, so I would like to be able to use it. 

---

Added by @choldgraf 

## Current status

**We wish to support Sphinx 3, and welcome PRs / assistance in getting the codebase ready for it**.

We know that there are some bugs that will be triggered by upgrading to Sphinx 3, and would love folks to help out in patching these so that we can support Sphinx 3 in MyST.

Here are some things you can do:

- **See [this `fix/sphinx-3` branch](https://github.com/executablebooks/MyST-Parser/tree/fix/sphinx-3)** and [the result of running the test suite](https://github.com/executablebooks/MyST-Parser/runs/899364125?check_suite_focus=true) for areas that will need some fixes. (e.g., for some reason Sphinx 3 stopped a bunch of intersphinx references from resolving?)
- Do a scan of the code base for items specified as deprecated in https://www.sphinx-doc.org/en/master/extdev/deprecated.html (the two main tasks here).

We're happy to review PRs and give pointers!

**Comment by choldgraf** [comment]
Mostly I think we've held off until a `3.1` comes out just assuming that there will be some bugs in there. See https://github.com/executablebooks/meta/issues/53 for a short mention of it.

I guess the question to figure out is: when do we say Sphinx 3 is supported? Is it as simple as "whenever the tests pass as-is (or with minimal changes) when using Sphinx 3?

Another question: if things break with Sphinx 3, do we want to start special-casing it where-needed? I've seen a lot of other projects do this but it definitely creates developer burden (e.g. lots of `try: except:` statements to catch API changes etc)

**Comment by chrisjsewell** [comment]
yeo cheers @choldgraf was just going to link to this.

I guess the main thing is that I/we wanted to "solidfy" the executable books stack first, in particular making sure the test infrastructure has very good coverage to detect where this introduces breaking changes, before potentially opening up a whole can of worms. We have enough issues to fix already, before dealing with sphinx 3 incompatibilities lol

**Comment by asmeurer** [comment]
To be clear, Sphinx 3.1 is out (the latest version is 3.1.2). 

I suspect this will start creating issues for people the longer you have the pin. If you only support one version of Sphinx I would rather it be the latest version.

**Comment by choldgraf** [comment]
@asmeurer ah I didn't realize that!

In the long run I agree w/ you we should be on the latest major version - it's just a question of "when", not "if"

**Comment by chrisjsewell** [comment]
Out of interest @asmeurer, what new features were you looking to use?

**Comment by asmeurer** [comment]
The ability to disable warnings on circular toctree references https://github.com/sphinx-doc/sphinx/issues/5128

**Comment by choldgraf** [comment]
I think another reality we're gonna run into is that, over time, we'll have more people coming from reading the Sphinx 3+ docs and "expecting" Sphinx to behave in the way that 3+ behaves, which will increasingly start to diverge from 2.x and may result in issues etc.

**Comment by asmeurer** [comment]
An issue I ran into was that I noticed I didn't have the latest sphinx and noticed conda didn't update it. So I tried `conda install sphinx=3`, but unfortunately conda is really bad at indicating why an install fails these days. I guessed that it was caused by myst, but other people might not guess so easily.

**Comment by choldgraf** [comment]
yeah we have run into similar issues in Jupyter, where we have to order the myst-parser in a particular way relative to the other installs or we will get version conflicts

**Comment by chrisjsewell** [comment]
> yeah we have run into similar issues in Jupyter, where we have to order the myst-parser in a particular way relative to the other installs or we will get version conflicts

I think you're talking about pip here not Conda. I think this was also due to sphinx being in the extras, which pip doesn't handle very well, and is now not the case.

> So I tried `conda install sphinx=3`, but unfortunately conda is really bad at indicating why an install fails these days

Well by default Conda won't let you introduce dependency version conflicts, which is a good thing IMO. What was the actual error message then?

**Comment by asmeurer** [comment]
Yeah pip lets you "workaround" version conflicts by clobbering them over each other, but that means that you either force install myst into an environment with sphinx 3 (if that's what you did then that's good because it means it probably already works or else the environment would have broken), or you install sphinx 3 but then later downgrade it when installing myst. 

> Well by default Conda won't let you introduce dependency version conflicts, which is a good thing IMO. What was the actual error message then?

If you create a new environment with just `myst_parser sphinx=3` it gives you a good message. The problem is if you install it into an existing environment with a lot of other packages, then it will tell you a lot of unrelated junk about every package that has a version restriction. Conda used to give good error messages once upon a time...

**Comment by chrisjsewell** [comment]
>  then it will tell you a lot of unrelated junk about every package that has a version restriction

fair

**Comment by chrisjsewell** [comment]
Just found out about this deprecation list: https://www.sphinx-doc.org/en/master/extdev/deprecated.html

**Comment by asmeurer** [comment]
That's a nice page. All libraries that do deprecations should try to collect all the deprecations into a single page like that.

**Comment by webknjaz** [comment]
Any updates on this? I wanted to integrate myst but saw that it downgrades sphinx version I already rely on so it's a blocker for me...

**Comment by chrisjsewell** [comment]
I personally won't have time to do this immediately I'm afraid. I've created the `fix/sphinx-3` branch, to check the current status, and there are indeed issues that need to be addressed: https://github.com/executablebooks/MyST-Parser/runs/899364125?check_suite_focus=true
(for some reason its stopped a bunch of intersphinx references from resolving?) 

If anyone has time to look into them and/or do a scan of the code base for items specified as deprecated in https://www.sphinx-doc.org/en/master/extdev/deprecated.html (the two main tasks here) that would be appreciated.

Or I can release an alpha version, with the pinning removed, but obviously with the caveat that there are definite bugs

**Comment by choldgraf** [comment]
I'm gonna hijack part of @asmeurer 's top-level comment to add this context in case others have a chance to help out

**Comment by asmeurer** [comment]
That's fine with me

**Comment by chrisjsewell** [comment]
Definitely want to help (where possible) integrating this into ansible repos though @webknjaz, since I'm a big user/fan 😄

**Comment by webknjaz** [comment]
@chrisjsewell well, it's not for ansible/ansible itself but for a subproject that I'm helping with (ansible/pylibssh). There's also ansible/ansible-lint that already has myst integrated to render a contributing file. Though, I may tell the docs team to consider adding myst if that's possible/desirable (the core docs is a complex mix of various inputs so it may be hard to achieve).

**Comment by ssbarnea** [comment]
I hope to see this fixed soon as 2.x has no future, 3.x is already more than stable. Until this is addressed, it seems better to hold-off my plans to `.rst` to `.md` migration plans.

**Comment by sbliven** [comment]
I'm looking forward to `:meta public/private:` for fine grained control of what gets included by autodoc. I was confused why it wasn't working until I noticed my sphinx was pinned < 3.

**Comment by chrisjsewell** [comment]
[version 0.10.0](https://github.com/executablebooks/MyST-Parser/blob/master/CHANGELOG.md#0100---2020-08-07) now released. Over to you guys!

**Comment by choldgraf** [comment]
amazing! ping @webknjaz as I know you were waiting for Sphinx 3 :-)

**Comment by webknjaz** [comment]
Thanks for the ping. I was already subscribed for the thread and releases :)
FWIW this will make @ssbarnea happy too
