### ISSUE TITLE
Why curly braces for block-level directives?

### ISSUE THREAD

**Issue by echarles** [executablebooks/MyST-Parser#185]
This may have been discussed before, but I am curious to know why [curly braces are needed for block level directives](https://myst-parser.readthedocs.io/en/latest/using/intro.html#block-level-directives-with-myst-markdown)?

Instead of 
```
```{directivename} <directive arguments>
:optionname: <valuename>

<directive content>
```
```

we could have the following which would be lighter while typing.

```directivename <directive arguments>
:optionname: <valuename>

<directive content>
```

**Comment by chrisjsewell** [comment]
Primarily to distinguish between what are highlighting languages, i.e.

````
```python
This text should be highlighted as python code

```
````

and what are directive names, i.e.

````
```{python}
This text should be interpreted by a directive named 'python' 

```
````

**Comment by choldgraf** [comment]
And specifically, the reason to use _curly braces_ is to draw inspiration from the pattern that the RMarkdown community uses, which in some ways has become a standard there for "this is not a regular Python block but does special stuff instead" (https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html)

**Comment by echarles** [comment]
yes, this sounded to me like RMarkdown indeed. I can see the argument for `python vs {python}` in a pure `myst-parser` context, but would prefer `python` only in a `myst-nb` context. In the notebook context, the user want to explore with code/markdown quickly and the curly brace is a bit too much for me.

But absolutely, I can see 2 reasons to leave it like that:

1. Have the same syntax for myst-parser and myst-nb
2. Align with the well known RMarkdown. 

I guess I will get used to the braces.

**Comment by echarles** [comment]
PS: I am in the scenario where a native myst format is written and run by the user as a notebook, exactly like RStudio does it with RMarkdown.

**Comment by choldgraf** [comment]
though if MyST Notebooks *didn't* use curly braces, how would you specify that you *don't* want a Python chunk to be run? Many notebooks also include literal python (e.g. for demonstrations)

**Comment by echarles** [comment]
Yep, I have reloaded RStudio which supports `python` (Knitr will generate a block text with highlights) vs `{python}` which will be run.

Closing this issue, sorry for the noise, and thx for your answers.
