### ISSUE TITLE
Support specialized role

### ISSUE THREAD

**Issue by SG-phimeca** [executablebooks/MyST-Parser#188]
The [specialized role feature](https://docutils.sourceforge.io/docs/ref/rst/roles.html#specialized-roles) of ReST allows to input inline raw code.
Supporting this feature would allow among other for punctual use of latex formating commands that have no equivalent in markdown, nor ReST.

It relies on the `raw` directive which is functionning well with MyST (as any other “normal” directive).
However, adding (as suggested in the documentation linked above) the following somewhere (say in `rst_prolog`):

    .. role:: raw-latex(raw)
       :format: latex

does not produce the expected result. The code latex (or html or whatever) raw code is not interpreted. Instead something like `:raw-latex:‘RAW_CODE_TO_BE_INTERPRETED‘` is typeset in way as to indicate a problem (it depends on the output processor).

**Comment by chrisjsewell** [comment]
Well you should still be using the role in the myst format: ``{raw-latex}`RAW_CODE_TO_BE_INTERPRETED` ``

**Comment by SG-phimeca** [comment]
> You should still be using the role in the myst format: `` {raw-latex}`RAW_CODE_TO_BE_INTERPRETED` ``?

Yes, that is what I used and yields the unintended result mentioned.

**Comment by chrisjsewell** [comment]
This should be closed in dcbd5ef, can you give it a go?

Note, the role definition should also be written in MyST, i.e 

````md
```{role} raw-latex(raw)
:format: latex
```

{raw-latex}`\tag{content}`
````

**Comment by SG-phimeca** [comment]
It works. Is there a way to pur the role definition in the conf.py configuration file ? Idealy this should not be in content source file.

**Comment by chrisjsewell** [comment]
cheers I've moved the configuration part to a seperate issue (#190)

**Comment by chrisjsewell** [comment]
closed by #189

**Comment by tavin** [comment]
This is a handy trick. Looking also at [docutil_directives.md](https://raw.githubusercontent.com/executablebooks/MyST-Parser/e0cf7da338f4c345f9f4e2dc490270c8db427020/tests/test_renderers/fixtures/docutil_directives.md) I would guess that I should be able to do something like this as well:

    ```{raw} raw
    :format: latex

    \tag{content}
    ```

Why doesn't it work? Is it mandatory to define a role?

**Comment by gl-yziquel** [comment]
Is there a way to get that to work in the javascript based mystmd ? Or is this possible only for the sphinx based myst parser ?
