### ISSUE TITLE
myst-parser 0.12.0 fails with No module named 'markdown_it.extensions.dollarmath'

### ISSUE THREAD

**Issue by echarles** [executablebooks/MyST-Parser#220]
I open this further to https://github.com/jupyterlab/benchmarks/pull/20

We have upgraded to 0.12.0 in the RDT build fails (pinning to 0.11.2 fixes the issue)

```
    from myst_parser.main import default_parser, MdParserConfig
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterlab-benchmarks/envs/latest/lib/python3.7/site-packages/myst_parser/main.py", line 13, in <module>
    from markdown_it.extensions.dollarmath import dollarmath_plugin
ModuleNotFoundError: No module named 'markdown_it.extensions.dollarmath'
```

**Comment by chrisjsewell** [comment]
Hmm, I haven't had any issues with this 🤔 You need markdown_it_py >= 0.5, which 0.12.0 should pin: https://github.com/executablebooks/MyST-Parser/blob/e7a2ba6088f5c731ba123ba52f29dfa60ca248e4/setup.py#L40

How are you installing and what version of markdown-it-py do you get?

**Comment by chrisjsewell** [comment]
I found your issue 😄

**Comment by echarles** [comment]
Thx a lot @chrisjsewell Issue is now fixed

For background, those deps definition have been copied from this repo. I have opened some time ago https://github.com/executablebooks/MyST-Parser/issues/155 which could help to have stable version definition (so may be less pinning).

**Comment by chrisjsewell** [comment]
Yeh no worries that still on the TODO! but... if you do copy all the dep definitions then you also need to re-copy all of them when you upgrade 😉 

Although really its not necessary to copy them all, you should just have in your setup.py the packages you directly depend on, rather than also their dependencies
