### ISSUE TITLE
Upgrading jupytext support

### ISSUE THREAD

**Issue by parmentelat** [executablebooks/MyST-Parser#236]
Hi; I just rebuilt my docker images and am facing a regression:

## with most recent release 

```
$ pip show myst-parser
Name: myst-parser
Version: 0.12.6
...

$ jupytext --to py:percent 1-99-quiz-python.md 
[jupytext] Reading 1-99-quiz-python.md
/opt/conda/lib/python3.8/site-packages/jupytext/myst.py:76: UserWarning: myst-parse failed unexpectedly: default_parser() got an unexpected keyword argument 'disable_syntax'
  warnings.warn("myst-parse failed unexpectedly: {}".format(err))
[jupytext] Writing 1-99-quiz-python.py in format py:percent
```

## going back to 0.11

```
$ pip install myst-parser==0.11
<...>
$ jupytext --to py:percent 1-99-quiz-python.md 
[jupytext] Reading 1-99-quiz-python.md
[jupytext] Writing 1-99-quiz-python.py in format py:percent (destination file replaced)
```

the sample notebook can be found here
https://raw.githubusercontent.com/ue12/python-numerique/8c3d0afed6d449f88111184401b9505e05c05327/notebooks/1-99-quiz-python.md

this has rather devastating consequences to me, as my students can no longer see the material as notebooks but as a botched md instead; please let me know what is happening here; looks like something on your end, is that correct ?

**Comment by chrisjsewell** [comment]
This is a known issue that I am about to fix today https://github.com/mwouts/jupytext/issues/591

**Comment by chrisjsewell** [comment]
The current "fix" is to use an earlier version of jupytext

**Comment by parmentelat** [comment]
fair enough

have you got a sense about when all this will make it on `pypi`, so that a regular build (i.e. with `pip` using the latest releases) will work again ? if it's a matter of days, it's maybe simpler for me to just wait instead of pinning/unpinning version numbers all over the place ;-)

otherwise, are you positive it's jupytext that needs to have its version pinned down ? my experiment was only about the version of `myst-parser` - otoh I haven't recorded the version of jupytext in both cases...
if so, what version of jupytext should be used ?

thanks for the prompt answer !

**Comment by chrisjsewell** [comment]
Well yeh you need to have myst-parser 0.8. 
But hopefully, it will be a matter of days 🤞

(There is a warning about this in https://myst-nb.readthedocs.io/en/latest/examples/custom-formats.html#using-jupytext)

**Comment by chrisjsewell** [comment]
See mwouts/jupytext #599

**Comment by chrisjsewell** [comment]
A release candidate is available here:

pip install jupytext==1.6.0rc0

😀
