### ISSUE TITLE
Intersphinx, inline role vs. Markdown syntax

### ISSUE THREAD

**Issue by pauleveritt** [executablebooks/MyST-Parser#246]
**Describe the bug**

The inline reference link syntax works with Intersphinx. I can't get the Markdown syntax to work.

**To Reproduce**

In the following, the first generates a working link. The second generates a link but the `href` isn't expanded.

```markdown
- {ref}`Myst Reference <myst:howto/autosectionlabel>`
- [myst ref](myst:howto/autosectionlabel)
```

**Environment**

- Python 3.8
- Sphinx 3.2.1
- myst-parser 0.12.8
- macOS

**Additional context**

I'm working on a Sphinx+MyST tutorial.

**Comment by chrisjsewell** [comment]
At a first guess, I'd say that you have not set `myst_url_schemes=["http", "https", "mailto"]` or similar (see https://myst-parser.readthedocs.io/en/latest/using/intro.html#myst-configuration-options).

This is to help MyST distinguish between URL schemes and references containing a colon `:`.

**Comment by chrisjsewell** [comment]
Pretty sure this will solve it, but let me know, and also if there should be anywhere in the documentation to make this clearer. (in `jupyter-book` the above is set as the default, because that is a more "opinionated" configuration)

**Comment by pauleveritt** [comment]
Yes, that did it! Sorry, I read and re-read that part about the config value. But I wasn't thinking of my Intersphinx tutorial section at that point, and...well....forgot.

Thanks for the fast response.
