### ISSUE TITLE
parser = default_parser("html") is broken

### ISSUE THREAD

**Issue by parmentelat** [executablebooks/MyST-Parser#247]
**Describe the bug**

I have just upgraded myst-parser and my code is now broken

**To Reproduce**

with the latest release 

```
$ pip show myst-parser
Name: myst-parser
Version: 0.12.8
```

if I run the following lines as extracted from readthedocs 
https://myst-parser.readthedocs.io/en/stable/using/use_api.html#the-parser

```
from myst_parser.main import default_parser
parser = default_parser("html")
parser
```

I get 

```
In [1]: from myst_parser.main import default_parser
   ...: parser = default_parser("html")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-072fd5f4ade0> in <module>
      1 from myst_parser.main import default_parser
----> 2 parser = default_parser("html")

~/miniconda3/envs/nbautoeval/lib/python3.6/site-packages/myst_parser/main.py in default_parser(config)
     62 def default_parser(config: MdParserConfig) -> MarkdownIt:
     63     """Return the default parser configuration for MyST"""
---> 64     if config.renderer == "sphinx":
     65         from myst_parser.sphinx_renderer import SphinxRenderer
     66

AttributeError: 'str' object has no attribute 'renderer'
```

**Expected behavior**

the way the doc says the code should behave

**Environment**

- Python Version [e.g. 3.7.1]:
```
python --version
Python 3.6.10 :: Anaconda, Inc.
```

same error with 3.8.5

- Operating System:

macOS and linux

**Additional context**

**Comment by parmentelat** [comment]
of course the bug maybe is just a missing change in the doc ?

**Comment by chrisjsewell** [comment]
Ah yeh my bad, forgot to update that part of the docs.
`default_config` now takes an `MdParserConfig` instance (a nice way to validate and store all the config in a single object)

```python
from myst_parser.main import default_parser, MdParserConfig
config = MdParserConfig(renderer="html")
default_parser(config)
```

**Comment by parmentelat** [comment]
Thanks !

while I'm at it, my code used to do 

```
parser.disable("math_single").disable("math_inline")
```

but I am now receiving

```
ValueError: MarkdownIt. Failed to disable unknown rule(s): ['math_single']
```

any clue on how to adapt that part ?

**Comment by chrisjsewell** [comment]
Yeh "math_single" is not a thing anymore, when I moved from using the texmath plugin to dollarmath (see https://markdown-it-py.readthedocs.io/en/latest/plugins.html)

**Comment by chrisjsewell** [comment]
Obviously if you are just using the markdown parser, you can always directly use markdown-it-py (I recently updated jupytext to not rely on myst-parser, https://github.com/mwouts/jupytext/commit/cf992bd90013c9f17dcedef7ae6ead3992bdf530)

**Comment by parmentelat** [comment]
***THANKS*** for the tip, I am indeed going to try and use `markdown_it` directly, if I can the right combination of settings that my code relies on;
