### ISSUE TITLE
Front matter dates causes the parser to choke

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#252]
If you put a date in your YAML front-matter, then the docutils renderer will choke with this error:

```
TypeError: Object of type date is not JSON serializable
```

The error pops up here:

https://github.com/executablebooks/MyST-Parser/blob/master/myst_parser/docutils_renderer.py#L941

I think YAML is parsing the field with an actual Python object, which is then breaking the JSON conversion.

Given that dates are a common field, perhaps we can special-case the date? Or we could add type `date` to the classes that are passed to `str()`

**Comment by chrisjsewell** [comment]
Yeh just add a serialisation rule for datetime objects here: https://github.com/executablebooks/MyST-Parser/blob/59ab5f376c9dd8c65839085a7874b1c12faf2df5/myst_parser/docutils_renderer.py#L940
