### ISSUE TITLE
Allow for admonition titles without specifying "admonition" when using ::: syntax

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#259]
I'm still not sure if this is a good idea or not, because it would technically break from Sphinx directives syntax, but:

I find that it feels unnecessarily complex to have to add `admonition` to my admonitions if I want them to have a title. E.g.:

```
:::{note}
Here is a note
:::
```

but if I want a title, I must do:

```
:::{admonition,note} My title
Here is a note
:::
```

I wonder what folks think about supporting the following condition:

- If `:::` syntax is being used
- If there is text in the body of the admonition (e.g. after the `:::` line)
- Then treat any text coming at the end of the `:::` line as a title, and auto-magically use the `{admonition,note}` pattern shown above.

That way users could do:

```
:::{note} My note title
My note body
```

but if they did:

```
:::{note} My note body
:::
```

then the title would be `Note`

What do folks think?

**Comment by chrisjsewell** [comment]
possibly 🤔 
FYI, its something that I didn't originally include in my https://github.com/executablebooks/meta/issues/149 list (adding now), but I want to also at some point re-appraise these `:::` blocks, and how they can be generalised, e.g. for use with things like the sphinx-panels panels/tabbed directives (just anywhere that the content of the directive is fully/mostly Markdown compliant)

**Comment by choldgraf** [comment]
that makes sense - I don't think this is a crucial or a super time-sensitive feature, just a feeling that has been nagging me as I use it. That said, if we're going to generalize `:::` to be more like "any directive that also supports entirely markdown content", then I think we may wanna just keep it as-is

**Comment by chrisjsewell** [comment]
again #273 kinda precludes this
