### ISSUE TITLE
Partial includes with the `include` directive

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/MyST-Parser#265]
**Is your feature request related to a problem? Please describe.**

I'd like to partially include my README, so that I can have the same contents for my project's initial introduction but can have different content beyond a point.

(in README, I'd add the contributing info + license info; in the docs' `index.md` I'd add the toctree and the information to guide the user's journey)

**Describe the solution you'd like**

Something similar to how [reStructuredText's include directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include) has the `end-before` and `start-after` options.

Here's an example of how that'd work, with user-provided comments in the markdown document.

````
```{include} ../README.md
:end-before: <!-- end-include-here -->
```

```{include} ../README.md
:start-after: <!-- start-include-here -->
```
````

**Describe alternatives you've considered**

None -- but mostly because I'm feeling a little lazy. :3

**Additional context**

https://docutils.sourceforge.io/docs/ref/rst/directives.html#include -- I JUST realized the reST has partial includes capability and I'd love to use it with MyST. :)

**Comment by choldgraf** [comment]
Does this not already work? I kinda feel like it should already work...

**Comment by pradyunsg** [comment]
Indeed -- this does work! Sorry for the noise!

(HUH. I swear I tried this before filing the issue, and it didn't work. Maybe I'm messed up which tab I was looking at?)
