### ISSUE TITLE
Using autosummary

### ISSUE THREAD

**Issue by rth** [executablebooks/MyST-Parser#268]
Thanks for this great package!

I was wondering if anyone managed to make `autosummary` work in combination with MyST-parser?

For instance, currently I have,
```markdown
(Note: ! added to escape code blocks)

!```{currentmodule} mypackage
!```
  
  
!```{autosummary}
:toctree: ./generated/

mypackage.func_a
mypackage.func_b
!```

```
and in sphinx `conf.py`,
```py
extensions = [
      ...
      "sphinx.ext.autosummary",
]
autosummary_generate = True
```

This kind of works and I get a table of functions,

![image](https://user-images.githubusercontent.com/630936/97776330-7137dd00-1b67-11eb-85ca-103634d49d3c.png)
though the formatting is a bit off. However, even with `autosummary_generate = True` the individual pages for functions are not generated.

In the build logs, one can see,
```
docs/my_module.md.rst:11: WARNING: autosummary: stub file not found 'mypackage.func_a'. Check your autosummary_generate setting.
```
Now I can't also run [sphinx-autogen](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#sphinx-autogen-generate-autodoc-stub-pages) because it expects rst files not markdown. 

Would you have any suggestions? The only workaround I can see is to manually run md2rst conversion and then run sphinx-autogen manually..

**Comment by chrisjsewell** [comment]
Heya! I imagine this suffers the same as issue as `autodoc`: https://myst-parser.readthedocs.io/en/latest/using/howto.html#use-sphinx-ext-autodoc-in-markdown-files
Have you tried the `{eval-rst}` approach?

> (Note: ! added to escape code blocks)

FYI you can just wrap the code fence with more `` ` `` to include them internally 😄 e.g.

`````

````markdown

```{hallo}
there
```

````

`````

**Comment by rth** [comment]
Thanks `{eval-rst}` works perfectly!

> FYI you can just wrap the code fence with more ` to include them internally smile e.g.

Thanks for the tip!

**Comment by rth** [comment]
> FYI you can just wrap the code fence with more ` to include them internally

By any chance @chrisjsewell you wouldn't know how to do that for inline links? e.g.
```
{ref}``  `function_name` <reference>``
```
doesn't visually render as `function_name` (with a link). Hard to know the right key words to search for this stuff..
