### ISSUE TITLE
Allow for `:::admonition` syntax (without curly brackets)

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#271]
Right now our special admonition syntax uses the same curly-bracket structure that we use for directives. AKA:

````
```{note}
my note
```
````

is equivalent to

```
:::{note}
my note
:::
```

What do people think about supporting the Pandoc-style of admonition classes w/o curly brackets:

```
:::note
my note
:::
```

This could be a comma-separated list of admonition labels, so we could allow for `:::note,admonition` and this would behave like `:::{note,admonition}`.

One benefit of this would potentially be interoperability with other markdown specs. For example, in HackMD `:::info` blocks will render as special "info" blocks, whereas the curly brackets are a more MyST-specific thing so less likely to interoperate with other flavors of markdown.

**Comment by chrisjsewell** [comment]
I think if you want this it should work a bit like the code fences, in that they would be interpreted as a special case.

i.e.

we intepret

````
```python
...
```
````

as

````
```{code-block} python
...
```
````

note I was thinking of just making these `:::` blocks act the same as ```` ``` ```` blocks, as in the content inside would not be parsed initially by the markdown-it-py parser, but in a recursive manner by myst-parser. Then they would just work for any directive (maybe making a special case for https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#markdown-figures)

**Comment by choldgraf** [comment]
Yeah - so something like:

```
:::note
my note
:::
```

would be interpreted as 

````
```{note}
my note
```
````

?

I actually looked into the HackMD reference and it seems like it could be a nice reference to work from. It's all based on markdown-it extensions and they're all listed here:

https://hackmd.io/c/codimd-documentation/%2F%40codimd%2Fmarkdown-syntax

here's the one about their "container" behavior:

https://hackmd.io/c/codimd-documentation/%2F%40codimd%2Fmarkdown-syntax#markdown-it-container

Obviously we probably don't wanna just copy over the same extensions etc, but could be a nice comparison

**Comment by chrisjsewell** [comment]
yep there already a lot of these extensions in markdown-it-py/myst-parser 👍
see https://markdown-it-py.readthedocs.io/en/latest/plugins.html
or if there are more you see, add them to https://github.com/executablebooks/markdown-it-py/issues/23

**Comment by chrisjsewell** [comment]
note also parsing direct url links (like https://example.com) is coming soon: https://github.com/executablebooks/markdown-it-py/pull/78

**Comment by chrisjsewell** [comment]
I'm closing this, because in #273 `:::` now act exactly the same as ```` ``` ````, which precludes not having the curly braces
