### ISSUE TITLE
Specify how shorthand directive options are parsed

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/MyST-Parser#280]
**Is your feature request related to a problem? Please describe.**

The [parameterizing directives](https://myst-parser.readthedocs.io/en/latest/using/syntax.html#parameterizing-directives) section states that:

- Directives may have YAML frontmatter, **parsed by the YAML formatter**
- Directives may have shorthand `:options:` instead

It is never specified how the shorthand options are parsed. Is

````
```test
:a: |
  yaml-formatted multiline text
```
````

correct?

**A link to the documentation page where you see an issue.**

https://myst-parser.readthedocs.io/en/latest/using/syntax.html#parameterizing-directives

**Describe the solution you'd like**

I would prefer it if the documentation specified how the values of the shorthand directive options are parsed.

**Comment by choldgraf** [comment]
Ah - is the main question whether the shorthand config is parsed in some other way than the YAML parser? Agree that should be made clear if I’m understanding you right.

**Comment by akhmerov** [comment]
Indeed. I've encountered this when trying to understand https://github.com/executablebooks/jupyter-book/issues/742. There the problem arises from parsing `:key: value: with a colon`, and the error indicates that the yaml parser is involved.

However I think the situation is confusing to the users because `:key: value` isn't valid yaml in the first place. Therefore the user doesn't necessarily have an expectation of what happens to the `value`. Is *any* yaml allowed there? Can it be spread over multiple lines?

**Comment by choldgraf** [comment]
Ah yeah it's the same parsing. The shorthand is just the : leading each line to *detect* the yaml ok the other side, but isn't part of the yaml itself. Eg without the short hand there are some examples of raw multi line yaml. 

Want to make a PR adding this context to the place(s) where you think it'd naturally be?

**Comment by akhmerov** [comment]
Ah, I see. so **each** line must start with a `:`, and not only those with the option name. I was confused by the similarity between the shorthand syntax and the rst options formatting.

**Comment by choldgraf** [comment]
Exactly - thanks for helping clarify with the PR!
