### ISSUE TITLE
myst_substitutions containing `>` cause a newline to be prepended and appended

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/MyST-Parser#282]
**Describe the bug**

When using myst_substitions where `myvar` is substituted with `">=1.2.3"`, the substitution removes the `>` and prepend and appends a new line. The `>` seem to cause it to happen. Perhaps because it was considered an unsafe character triggering logic that ended up prepending and appending the new line?

**To Reproduce**

```python
# conf.py
myst_enable_extensions = [
    "substitution",
]
myst_substitutions = {
    "my_var_1": ">=1.2.3",
    "my_var_2": "=1.2.3",
}
```

```
# myst-content.md
BEFORE{{my_var_1}}AFTER

BEFORE{{my_var_2}}AFTER
```

Observe output like this

![image](https://user-images.githubusercontent.com/3837114/103501742-6b07fa80-4e4f-11eb-845e-302f5b7de510.png)

**Environment**

- Python version: 3.7.6
- Package versions or output of `jupyter-book --version`:
  ```
  Jupyter Book: 0.9.1
  MyST-NB: 0.10.1
  Sphinx Book Theme: 0.0.39
  MyST-Parser: 0.13.1
  Jupyter-Cache: 0.4.1
  NbClient: 0.4.0
  ```
- Operating System: Ubuntu 20.04

**Comment by chrisjsewell** [comment]
hey if you backslash escape: `\>=1` then it should output correctly, basically it is parsing as a block quote without the escape:

>=1.2.3

I'm not sure if there is a good "fix" to this, to add to the code, but I'll think on it

**Comment by choldgraf** [comment]
Hmmm - we should start off by documenting these edge-cases and potential ways around them (like using `\`). I could see this confusing others as well. Perhaps another approach would be to include them as literal text? (e.g. `` `>=1.2.3` ``).

**Comment by chrisjsewell** [comment]
Yeh markdown-it-py records whether the substituition is inline or not, but as discussed in https://github.com/executablebooks/MyST-Parser/issues/279#issuecomment-752948379, its a bit of a trade off between either:

1. Always parse inline substitutions as inline (i.e. ignore block syntaxes): this means you would not have this issue, but then you could not substitute directives into inline positions which, particularly for images and/or inseting thinks into table cells, is pretty useful
2. Always parse a block, but then you can get some edge cases for simple text substitutions, e.g. starting with blockquote syntax `>` or list syntax `- `, `* ` etc

Other options:

Perhaps for inline substitutions, we could check for these common block prefixes (`>`, `-`, `*`, etc) and either escape them or switch to parsing inline

Or inversely check if an inline substitution starts with directive syntax ```` ```{ ```` and only then parse it as a block (parse inline otherwise)
