### ISSUE TITLE
Direct support for `meta` directive

### ISSUE THREAD

**Issue by tfiers** [executablebooks/MyST-Parser#284]
[Sphinx's `meta` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#html-metadata) adds `<meta>` tags to the `<head>` of the page.

This is very useful. One of my usecases is adding `<link rel="canonical">` tags to [Hypothesis-annotated Jupyterbook pages](https://jupyterbook.org/interactive/comments/hypothesis.html) so that the annotations don't disappear when the filename/location changes.

The `meta` directive doesn't work yet alas:
`Directive 'meta' cannot be mocked: MockingError: MockState has not yet implemented attribute 'nested_list_parse'`

I'm up for contributing a patch. This would be my first time contributing to an executablebooks project. Could a maintainer give me a pointer for getting started in the codebase here on this problem?

(my current solution is a custom build script that edits the generated html with `lxml` after `jb build`)

**Comment by choldgraf** [comment]
Agreed this would be useful! I think there are two ways this could be done:

1. Add the method in the error above to `MockState`. I think that'd be a change to the following link w/ a similar pattern to the other methods seen there: https://github.com/executablebooks/MyST-Parser/blob/750ea18db6e7eccc147e3bf45921ac4eb6715ab5/myst_parser/mocking.py#L66
2. Special-case "HTML meta tags" in the FrontMatter for MyST documents (https://myst-parser.readthedocs.io/en/latest/using/syntax.html#front-matter)

number 2 feels a bit more natural to me, though is technically a departure from how rST handles this. Maybe @chrisjsewell has an opinion?

**Comment by chrisjsewell** [comment]
yeh its a bit of a tricky one to mock, in the directive logic.
I'd not firstly though that it is supported, via the use of `eval-rst` (see https://myst-parser.readthedocs.io/en/latest/using/syntax.html#how-directives-parse-content)

````
```{eval-rst}
.. meta::
  :key: value
```
````

As a quick fix, the error message could perhaps mention using this

**Comment by chrisjsewell** [comment]
To elaborate a little further, in:

```
.. meta::
   :description lang=en: An amusing story
   :description lang=fr: Une histoire amusante
```

those `description` are not actually options of the directive, they are its content, but MyST-Parser does not (as yet) have a syntax for field lists.
So even if you implemented `nested_list_parse` it still would not work

**Comment by chrisjsewell** [comment]
but yeh could consider (2)

**Comment by tfiers** [comment]
Thanks for the help!

I didn't know about `{eval-rst}` (didn't re-read the JupyterBook docs for a while).
I made a PR that points to it in the error message, as suggested: #285

Am I right that FrontMatter is only applicable to `.md` files, and not Jupyter notebooks?

For the use case mentioned above (a `<link rel="canonical">` tag for migrating Hypothesis comments), I still need [my custom HTML-rewriting solution](https://github.com/tfiers/voltage-to-wiring-sim/blob/6bb515fe03f4b9c40d6678ba8f1461e80a33b794/website/build.py#L65), as each Sphinx page already contains a `<link rel="canonical">` tag (supposedly added [here](https://github.com/sphinx-doc/sphinx/blob/7ecf6b88aa5ddaed552527d2ef60f1bd35e98ddc/sphinx/themes/basic/layout.html#L136)). I thus need to find and remove these, and then add my own. And besides, this tag is not even a `<meta>` tag.

When I do use a `<meta>` tag I sometimes want it on one page, and sometimes on every page, e.g. `<meta name="robots" content="noindex" />` (all pages) versus `<meta name="google-site-verification" content="…" />` (home page only).

Given this, and the fact that `{eval-rst}` exists, I won't be adding direct support for the `meta` directive now.

**Comment by chrisjsewell** [comment]
> Am I right that FrontMatter is only applicable to .md files, and not Jupyter notebooks?

No, for notebooks the top-level metadata is read as the front matter. 

I could envisage potentially having a sphinx setting for project wide default front-matter/metadata, of which meta could be a part
