### ISSUE TITLE
syntax for field list and option list?

### ISSUE THREAD

**Issue by idnsunset** [executablebooks/MyST-Parser#286]
**Is your feature request related to a problem? Please describe.**

First thanks to you guys for developing MyST for those who use Sphinx but prefer Markdown over RST.

RST supports field list and option list which are given in the following syntax:

```rst
:field1: desc1
:field2: desc2
``` 

```rst
-shortopt, --longoption  desc2
```

I've read the documentation and MyST syntax doesn't seem to support these if I didn't miss something, which means that I have to use `eval-rst` directive as a workaround, right?

**Describe the solution you'd like**

Any plan to add special syntax to deal with these two? There is of course no problem If you think `eval-rst` is sufficient.

**Comment by chrisjsewell** [comment]
Out of interest, what would you use these syntaxes for?

**Comment by choldgraf** [comment]
And yep, as of right now these aren’t supported in myst and we recommend the eval rst approach if you need them in your book 👍

**Comment by idnsunset** [comment]
> Out of interest, what would you use these syntaxes for?

The field list is often used to give author, date or any other information to an article or a section.
The option list is used for listing command options. 

In RST, they are all rendered as table or definition list with particular `class` attribute, which is easy for styling. If they are supported to produced the same elements as RST does, then I can could use any Sphinx them styling them correctly.

Anyway, not a big deal, thanks for your responses!

**Comment by chrisjsewell** [comment]
Thanks,

Just to note, at the article level, using front-matter is equivalent to using a field list at the start of a document, e.g.

```md
---
author: Chris Sewell
---
```

is equivalent to:

```restructuredtext
:author: Chris Sewell
```

Neither of these are actually rendered by default in the document because, as explained in https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#file-wide-metadata, they are moved to the Sphinx environment

**Comment by chrisjsewell** [comment]
field lists are now available: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#field-lists
I don't intend to add option lists, though obviously others are welcome to try
