### ISSUE TITLE
Unexpected transition produced for footnote definitions

### ISSUE THREAD

**Issue by idnsunset** [executablebooks/MyST-Parser#287]
**Describe the bug**

```markdown
Footnote reference [^a]

[^a]: Definition for footnote a
```

The footnote definition produces:

```html
<hr class="docutils">
<dl class="footnote brackets">
  ...
</dl>
```

And even worse:

```markdown
---

[^a]: Definition for footnote a
```

causes error stating that at least one element is needed to separate two transitions. 

**Expected behavior**

Footnote definition shouldn't implicitly add a transition right there, as users may prefer to put a rubric block there and style it with a bottom line.  BTW, Sphinx with RST doesn't produce the transition.

**Environment**

- Python Version: 3.9.1
- MyST Version: 0.13.1
- Operating System: Debian

**Comment by chrisjsewell** [comment]
I can potentially make the transition insertion optional.

It is of note that footnotes in Markdown work different to RST (intentionally): in Markdown all footnotes are moved to the bottom of the document, whereas in RST they are not

so if you write

```markdown
### Footnotes

[^a]: Definition for footnote a

### Other

some other text

```

you will actually end up with essentially

```markdown
### Footnotes

### Other

some other text

[^a]: Definition for footnote a

```

The footnotes are intended to work more like LaTeX (https://www.overleaf.com/learn/latex/footnotes) and other Markdown renders and so, althoug I don't want to block you from doing it, I would not really recommend using rubric blocks

**Comment by idnsunset** [comment]
No matter a rubric block is there or not, the transition element doesn't belong to footnotes, it would be better for users to determine whether to have it. I usually style headings with a bottom border line,  then two successive horizontal lines feel really superfluous.

```
Footnoes
-------------
-------------
[1] xxx
```

If this transition element has some particular attribute other than `class="docutils`, which can distinguish it from other manually inserted transitions,  then we can style it as we like via CSS. However, for those who prefer to place all footnote definitions at the bottom of a document, an option to disable the transition element would be absolutely welcome.

Thanks for your quick response!
