### ISSUE TITLE
asciimath support

### ISSUE THREAD

**Issue by v217** [executablebooks/MyST-Parser#298]
Hi, thank you for this project!
Since mathjax is used, I was wondering if there is a way to enable http://asciimath.org/
 http://docs.mathjax.org/en/latest/input/asciimath.html
Thanks

**Comment by chrisjsewell** [comment]
Hi @v217 did you find a solution for this?

**Comment by v217** [comment]
Hi, not really, I just used `<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=AM_CHTML"></script>` from www.asciimath.org in the generated html.

**Comment by jimy-byerley** [comment]
Hello
Is there plans to include support for asciimath ? 
If find it far more readable in markdown than any *tex* syntax (even counting on macros). And the markdown syntax is meant to be easy to read and intuitive to write.
