### ISSUE TITLE
Issue with latest release?

### ISSUE THREAD

**Issue by OriolAbril** [executablebooks/MyST-Parser#299]
**Describe the bug**

Automatic doc building in CI started failing right after updating myst. See the full job [traceback](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3784&view=logs&j=d82cb496-a257-54da-46ee-b2e2bafff9ac&t=094ae290-cc0b-56df-4bea-746ee04ab50f&l=566). I copy below the piece that looks relevant to the issue at hand.

```markdown
Exception occurred:
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/myst_parser/docutils_renderer.py", line 79, in token_line
    raise ValueError(f"token map not set: {token}")
ValueError: token map not set: Token(type='front_matter', tag='', nesting=0, attrs=None, map=None, level=0, children=None, content={'celltoolbar': 'Raw Cell Format', 'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}, 'language_info': {'codemirror_mode': {'name': 'ipython', 'version': 3}, 'file_extension': '.py', 'mimetype': 'text/x-python', 'name': 'python', 'nbconvert_exporter': 'python', 'pygments_lexer': 'ipython3', 'version': '3.8.3'}, 'toc': {'base_numbering': 1, 'nav_menu': {}, 'number_sections': True, 'sideBar': True, 'skip_h1_title': False, 'title_cell': 'Table of Contents', 'title_sidebar': 'Contents', 'toc_cell': False, 'toc_position': {}, 'toc_section_display': True, 'toc_window_display': False}}, markup='', info='', meta={}, block=False, hidden=False)
The full traceback has been saved in /tmp/sphinx-err-fd1cvqyt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Environment**

- Python Version [e.g. 3.7.1]: 3.8
- Operating System: ubuntu

**Notes**
I will reproduce the issue locally as soon as I have time and try to generate a minimal example but I figured it may be worth it to post it and see if it has happened to other people.

**Comment by firasm** [comment]
Thanks @OriolAbril for posting the bug ! I was hit by this this morning just before my lecture but I managed to fix it thank to your report and @chrisjsewell ' fix!

I gotta remember to peg versions better in GH actions!

(in my case, I just set the version to 0.13.1)

**Comment by jakevdp** [comment]
+1 - I'm seeing this today as well.

**Comment by chrisjsewell** [comment]
patience 😜

**Comment by OriolAbril** [comment]
Cool, thanks @chrisjsewell, looks like it's not necessary to generate a minimal example. Thanks for the super quick fix.

**Comment by chrisjsewell** [comment]
fixed in new versions

**Comment by chrisjsewell** [comment]
myst-parser==0.13.3 and myst-nb==0.11.1

**Comment by donbowen** [comment]
@chrisjsewell My commit 3 days ago worked, but I just got this error tonight. Do I add
```

**Comment by chrisjsewell** [comment]
@donbowen do you have a link to your repository I can look at?

**Comment by donbowen** [comment]
Thanks for the quick reply! [It's here](https://github.com/LeDataSciFi/ledatascifi-2021). If you look at the [actions](https://github.com/LeDataSciFi/ledatascifi-2021/actions) you can see the "fix" commit failed 20 minutes ago but worked 3 days ago. (I reverted my commits today thinking I made a mistake.)

**Comment by chrisjsewell** [comment]
Ah I see, this should actually be fixed in the last commit to markdown-it-py (https://github.com/executablebooks/markdown-it-py/commit/fa1d3e3c338533e042c327e14d050c7a3a9a7a05, Fix missed mappings for table rows), which hasn't been released yet.
I will do a v0.6.2 release for that which should hopefully fix your issue

**Comment by chrisjsewell** [comment]
@donbowen ok thats done, so try re-running and let me know if that works? (if not first make sure markdown-it-py 0.6.2 is now being installed)

**Comment by donbowen** [comment]
That fixed it, thanks @chrisjsewell !
