### ISSUE TITLE
Sphinx extracts Markdown without inline markup

### ISSUE THREAD

**Issue by jpmckinney** [executablebooks/MyST-Parser#304]
**Describe the bug**

If the Markdown document contains:

```md
This is **bold text**.
```

Sphinx extracts into a POT file:

```
This is bold text.
```

**To Reproduce**

1. Clone https://github.com/jpmckinney/myst-parser-tests
2. Run instructions at https://github.com/jpmckinney/myst-parser-tests/blob/master/index.md

**Expected behavior**

It should extract:

```
This is **bold text**.
```

Otherwise, translators don't know which words to emphasize, since that information is lost.

**Comment by jpmckinney** [comment]
Note: We might still need something like #301.

cc @choldgraf

**Comment by chrisjsewell** [comment]
> https://github.com/executablebooks/MyST-Parser/pull/301#issuecomment-774348557

I guess I can close this then?

**Comment by jpmckinney** [comment]
@chrisjsewell If #301 is merged. Otherwise, this is still an issue.
