### ISSUE TITLE
to_html() output

### ISSUE THREAD

**Issue by farabolaza** [executablebooks/MyST-Parser#307]
The html output produced by to_html() doesn't seem to fully parse any rst-like features of myst, like roles and directives.

I don't know if it's intended to behave this way. 

**To Reproduce**

for instance
````
from myst_parser.main import to_html

test = ("""
Here's some *text*

1. a list

> a quote

{ref}`target`

```{glossary} my gloassary
name
    definition
```
"""
)


to_html(test)

<p>Here\'s some <em>text</em></p>\n<ol>\n<li>a list</li>\n</ol>\n<blockquote>\n<p>a quote
</p>\n</blockquote>\n<p>
<code class="sphinx-role">{ref}[target]</code>
</p>\n<pre><code class="language-{glossary}">name\n    definition\n</code></pre>\n
````
another input

````
t=("""
```{admonition} This is my admonition
This is my note
```
""")

to_html(t)
````

output

````
<pre><code class="language-{admonition}">This is my note\n</code></pre>\n
````

**Environment**

- Python Version [e.g. 3.7.1]: 3.8.5
- Package version (myst parser): 0.13.3
- Operating System: Windows

**Comment by chrisjsewell** [comment]
> I don't know if it's intended to behave this way.

Heya, yes it is; you have to use sphinx to fully parse to HTML

**Comment by chrisjsewell** [comment]
This function is explained in https://myst-parser.readthedocs.io/en/latest/using/use_api.html

**Comment by farabolaza** [comment]
Thanks for you answer, i read the api doc before posting here, but it wasn't really clear (at least to me, i'm not a programmer) that using sphinx was mandatory to get a fully parsed html output.

thanks again

**Comment by chrisjsewell** [comment]
yes thanks, as you see I've changed the label to `documentation` to perhaps make this more clear

**Comment by choldgraf** [comment]
Note that there may be some directives that we could natively parse and render one day (eg note directives) but it's unclear what would be the process to choose these directives. I think it's something to think about and explore though. If myst is popular enough, people will want to use it without the requirement for sphinx

**Comment by chrisjsewell** [comment]
Heya, I'm going to close this, since I updated the documentation and docstrings in #426
