### ISSUE TITLE
Finalise syntax

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/MyST-Parser#31]
Agree that all the core syntax elements are present, and their format is acceptable 

Related issues: 

- [ ] #4
- [x] #98

**Comment by chrisjsewell** [comment]
#4

**Comment by chrisjsewell** [comment]
Other syntax from rST to consider:

[Substitution references](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#substitutions), can be e.g. text, an image, a hyperlink, or (special) directive:        

```restructuredtext
 |sub|

.. |sub| image:: myimage.png
```

[Footnote references](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#footnotes) (also citation references are similar):

```restructuredtext
A footnote.[1]

.. [1] A numerical footnote
```

Also implemented in some flavours of Markdown (see [Extended Syntax](https://www.markdownguide.org/extended-syntax/#footnotes)):

```markdown
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.
```

**Comment by chrisjsewell** [comment]
Note to self; in the documentation, should also highlight the fact that MyST can do nested inline markup, which rST cannot, e.g. [Here's a link with *italic* text]().

**Comment by akhmerov** [comment]
My 5c: I didn't see a good use for substitution references, aside of counteracting other rst limitations/annoyances.

**Comment by choldgraf** [comment]
I'm "meh" on substitutions...it doesn't seem super useful to me given the added cognitive burden. Footnotes I think are worth implementing - I believe that Pandoc uses

```
[^myfootnote]

[^myfootnote]: My footnote text
```

syntax.

---

Sometimes I also wonder if the same syntax style could be used for sidebar notes, like:

```
This is [>mysidebarnote]

[>mysidebarnote]: And here is the sidebar note
```

but that's for a different issue :-)

**Comment by najuzilu** [comment]
It would be great to finalize the syntax for footnote references since we have a few test cases that use them. Another thing to consider regarding footnote references could be automatic enumerate numbering.

**Comment by mmcky** [comment]
re: `substitutions`. It isn't something we need straight away but I think substitutions are useful when building more complex tables. For example adding a multiline code block is harder to do inside of a table -- when you can use simple labels and substitute in the code blocks from a list below it.

**Comment by choldgraf** [comment]
@mmcky just a note that I've found that having markdown-style cell fences for directives has helped with this a bit. You have more control over the whitespacing etc which might make it easier to make these complex tables with directives

**Comment by chrisjsewell** [comment]
I think this is pretty locked in now
