### ISSUE TITLE
Markdown renderer (for translations)

### ISSUE THREAD

**Issue by jpmckinney** [executablebooks/MyST-Parser#311]
**Is your feature request related to a problem? Please describe.**

I have Markdown documents. I use them in Sphinx documentation, for which I have translations. I also use them in another project, which takes Markdown as input. Since I already have translations in Sphinx, I'd like to be able to use Sphinx to render the original Markdown as translated Markdown.

**Describe the solution you'd like**

Perhaps a method like `to_markdown` that matches the API of `to_docutils`, etc. Obviously, outside the context of translation, this method would have little purpose.

**Describe alternatives you've considered**

For now, I parse the Markdown document to a docutils document with `to_docutils` (see https://github.com/open-contracting/ocds-babel/blob/myst-parser/ocds_babel/translate_markdown.py), which I then walk with a node visitor (https://github.com/open-contracting/ocds-babel/blob/myst-parser/ocds_babel/markdown_translator.py) to output Markdown.

**Comment by chrisjsewell** [comment]
Note, there is already a Markdown renderer for markdown-it-py (i.e. text -> tokens -> text), which I think could be adapted/extended for this purpose: https://github.com/executablebooks/mdformat.

**Comment by jpmckinney** [comment]
I'll test some things out, but Poetry makes it incredibly complicated to develop against a development version of a Python package: https://github.com/python-poetry/poetry/issues/34

**Comment by chrisjsewell** [comment]
> I'll test some things out, but Poetry makes it incredibly complicated to develop against a development version of a Python package

you can take that up with @hukkinj1 😉

**Comment by hukkinj1** [comment]
Hey @jpmckinney, have you tried simply `poetry install`? That should be similar to `pip install -e .`, as in, you can change the Python files and your local `mdformat` installation will change accordingly.

**Comment by jpmckinney** [comment]
That works! Not sure how that Poetry issue got so long.

**Comment by jpmckinney** [comment]
So for this issue, I've opened on mdformat a documentation issue https://github.com/executablebooks/mdformat/issues/130 and a feature PR https://github.com/executablebooks/mdformat/pull/129

An issue is that, if the source Markdown has extra backticks for a code span, then mdformat will collapse them before translation. However, MyST-Parser extracts the Markdown with the extra backticks: https://github.com/executablebooks/MyST-Parser/pull/317 So, the PO/POT file will have extra backticks, but the translator will be passed a string without extra backticks, such that the string will not be translated.

Ideally, there would be an option for mdformat to retain the original backticks, so that the translation will work.

**Comment by jpmckinney** [comment]
With that mdformat PR, I'm able to use mdformat directly without MyST-Parser: https://github.com/open-contracting/ocds-babel/blob/mdformat/ocds_babel/translate_markdown.py#L18

However, there's just that backtick issue. I don't know if the solution is in MyST-Parser, mdformat, or if the problem needs to be pushed onto the user to provide input without extra backticks.

**Comment by hukkinj1** [comment]
So first of all a heads-up: `mdformat` is a _CommonMark_ compatible formatter and _GFM_ compatible via a plugin. Seeing that this issue was made in MyST-Parser repository I assume you have _MyST_ Markdown which isn't really supported currently. If the text you input contains any MyST specific syntax, weird things will happen as the formatter will interpret the document as if it was CommonMark.

Secondly, I'm not convinced we should build functionality in the formatter that changes content, as that's not really what formatters do. There is a plugin API and plugins are free break this rule however.

If I were you the first thing I'd try is to parse the Markdown with `markdown-it-py`. You'll get a list of tokens (the syntax token stream) which you can iterate and mutate to your liking (set the translations in place). Then use this token stream as input for the [`MDRenderer.render`](https://github.com/executablebooks/mdformat/blob/915f2ef4350346065a729a257f3ac81c060a28b1/mdformat/renderer/__init__.py#L29) method from `mdformat` to get a Markdown text document again.

**Comment by jpmckinney** [comment]
The Markdown I'm translating follows CommonMark (all the README.md files in https://github.com/open-contracting-extensions). I'm using Sphinx (in combination with MyST-Parser) to extract the strings to translate, because Sphinx extracts strings to gettext catalogs in a sane way, and I don't know another tool that does this.

I'll look into changing the text that's provided to the renderer as you suggest.

**Comment by jpmckinney** [comment]
@hukkinj1 I'm not sure your suggestion will work (without effectively duplicating mdformat).

Strings are translated at the block level (e.g. paragraphs). That's because word order can change from one language to another (e.g. subject-verb-object versus subject-object-verb languages), and if, say, the verb is emphasized, then the emphasized word will be in a different position in each language.

As far as I can tell, MarkdownIt can return an `inline` token with the block-level content in its `content` field, which is what I need to translate. However, if I change that `inline` token's content then call `MDRenderer.render`, I just get the original, untranslated input. To get it to work, I'd need to re-parse the translated text and splice in the tokens... or something.

Maybe I'm missing the obvious?

**Comment by jpmckinney** [comment]
Nevermind - writing that out made the solution clearer:

    parser = MarkdownIt()

    tokens = []
    for token in parser.parse(md):
        if token.type == 'inline':
            # raise Exception('\n'.join([repr(token), repr(parser.parse(translator.gettext(token.content))[1:-1])]))
            tokens.extend(parser.parse(translator.gettext(token.content))[1:-1])
        else:
            tokens.append(token)

    return MDRenderer().render(tokens, {}, {})

**Comment by hukkinj1** [comment]
:+1: 

I recommend doing:
```python
from markdown_it import AttrDict, MarkdownIt
from mdformat import MDRenderer

mdit = MarkdownIt()
env = AttrDict()
tokens = mdit.parse(md, env)
# ... mutate tokens here ...
text = MDRenderer().render(tokens, mdit.options, env)
```
that is, reuse the options and env structures in both parsing and rendering to have everything work as expected.

**Comment by jpmckinney** [comment]
Thanks! I just needed to import from `markdown_it.main` instead. And with this approach, the text that's passed to the translator still has the original backticks, so that edge cases isn't an issue.
