### ISSUE TITLE
sphinxcontrib-bibtex v2.2 triggers a bug in resolving references

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#312]
I just tried upgrading to the alpha version of `sphinxcontrib.bibtex`, and it triggers some bugs that seem to be related to resolving references via MyST.

Here's a PR that raises this error in sphinx-book-theme:

https://github.com/executablebooks/sphinx-book-theme/pull/288

link to failing docs build:

https://readthedocs.org/projects/sphinx-book-theme/builds/13012285/

I'm not positive if the bug is on the sphinxcontrib.bibtex side or the myst side, but opening this just to keep track of the issue.

**Comment by chrisjsewell** [comment]
As I've noted in https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/232#issuecomment-778766512, it was a bug in bibtex (not implementing `resolve_any_xref`), but there is a minor bug directly copied from sphinx. Very unlikely that it would manifest but can be fixed

**Comment by chrisjsewell** [comment]
see also https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/232#issuecomment-778767364

**Comment by chrisjsewell** [comment]
fixed in #313
