### ISSUE TITLE
Link from rst files to myst-markdown files

### ISSUE THREAD

**Issue by arwedus** [executablebooks/MyST-Parser#324]
**Is your feature request related to a problem? Please describe.**

When half of the documentation is in Markdown files and the other half is in reStructuredText, I am not able to reference a Markdown page from a rST file using MyST.

**Describe the solution you'd like**

If MyST generated page "references", like any rST page does, we could use something like :doc:\`MyMarkdownPageName\` to refer to the markdown page.

**Describe alternatives you've considered**

I have tried linkage by giving the page name or a relative path to the markdown file. Both ways failed.

**Additional context**

If you want, I'll provide a small executable example.

**Comment by chrisjsewell** [comment]
Heya, yeh definitely if you could provide a minimal example, because I'm 99% sure this is definitely already possible 😄

**Comment by arwedus** [comment]
It works, indeed. I got something wrong in my first try!
