### ISSUE TITLE
replacements extension: replace --> with →

### ISSUE THREAD

**Issue by PhilipMay** [executablebooks/MyST-Parser#328]
Hi,
could you maybe add the following replacement to your replacements extension:

Replace --> with →

Thanks
Philip

**Comment by choldgraf** [comment]
Just a note that I believe the place to make this enhancement would be in the [markdown-it-py package](https://github.com/executablebooks/markdown-it-py). Somewhere around here:

https://github.com/executablebooks/markdown-it-py/blob/49926455ba4829365a549074d39ef3598f98205d/markdown_it/rules_core/replacements.py#L3

**Comment by PhilipMay** [comment]
Thanks @choldgraf for the hint. I opened a FR there: https://github.com/executablebooks/markdown-it-py/issues/143

Closing this...
