### ISSUE TITLE
Add Task Lists as a MyST extension

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/MyST-Parser#330]
**Is your feature request related to a problem? Please describe.**

https://github.com/executablebooks/mdit-py-plugins/tree/master/mdit_py_plugins/tasklists exists!

**Describe the solution you'd like**

We should allow enabling it with MyST! That'll bring us closer to GFM, which is... neat, I guess. :)

**Describe alternatives you've considered**

Status quo, but that's not as nice.

**Additional context**

Coming from pradyunsg/furo#106.

**Comment by chrisjsewell** [comment]
Already on it https://github.com/executablebooks/jupyter-book/issues/1133

**Comment by pradyunsg** [comment]
Hurray! \o/

**Comment by chrisjsewell** [comment]
> closer to GFM

See a comment here: https://github.com/executablebooks/markdown-it-py/pull/136#discussion_r586851595, also https://github.com/executablebooks/markdown-it-py/commit/8901a52953dff6b4fad95994c15fdc46b91a5f23

**Comment by chrisjsewell** [comment]
closed in #370
