### ISSUE TITLE
myst_heading_anchors: Broken for headings with punctuation

### ISSUE THREAD

**Issue by jpmckinney** [executablebooks/MyST-Parser#331]
**Describe the bug**

With this in `conf.py`:

```py
myst_heading_anchors = 6
```

With the following Markdown:

```md
[Link](#heading-hyphen)
[Link](#example-1-1)

# Heading - Hyphen

# Example 1.1
```

A page is generated with:

```html
<h1>Heading - Hyphen<a class="headerlink" href="#heading-hyphen" title="Permalink to this headline">¶</a></h1>
...
<h1>Example 1.1<a class="headerlink" href="#example-1-1" title="Permalink to this headline">¶</a></h1>
```

However, although the link anchors match the heading anchors, the build warns:

```
WARNING: 'myst' reference target not found: #heading-hyphen
WARNING: 'myst' reference target not found: #example-1-1
```

And the `a` tags are not created (`<span class="xref myst">Link</span>` instead).

**To Reproduce**

Build this repo: https://github.com/jpmckinney/myst-parser-tests

**Expected behavior**

No warning. Links created.

**Environment**

myst-parser 0.13.5

**Comment by choldgraf** [comment]
Hmmm just to clarify, is this when auto generating section labels in myst?

**Comment by jpmckinney** [comment]
Note to self: Once this is fixed, I can restore:

* A few `annex-d...` links in european-union and european-union-support: https://github.com/open-contracting-extensions/european-union/commit/cae2a8e5759f18218bd1100fe8e3c8089333b4aa#diff-9957cb19840efc425a76191973cd35cf17efd567cfeda02a17d5b577dc078c97R20
* Links to examples in standard: https://github.com/open-contracting/standard/pull/1253/commits/dbd9117da87a5a9c959f8d8c364eb732bf084f1f#diff-0a32de0359d87c42644de479f85c247d27d5f0dbb0959f162fb4b8b9389b1bb6L32

**Comment by jpmckinney** [comment]
Yes, I forgot to mention, I'm using `myst_heading_anchors = 6` (added to issue description now).

**Comment by jpmckinney** [comment]
Aha, it's that the slugs are unexpected:

`heading---hyphen` and `example-11`

I don't really like these, but I guess some people might be depending on this behavior, so I'll just edit my refs accordingly.

**Comment by jpmckinney** [comment]
Actually, is there a way to set the `slug_func` on the `anchors_plugin`? MyST Parser only exposes `max_level`.

**Comment by jpmckinney** [comment]
I'm also wondering why the behavior of github-slugger was selected, and not the behavior of docutils/Sphinx, which uses `make_id` in `docutils.nodes` to generate IDs (which look like `heading-1` instead of `heading---1`, etc.).

**Comment by chrisjsewell** [comment]
> I'm also wondering why the behavior of github-slugger was selected

Well its because its as close to a standard as there is for these slugs, and means that they will also work in a wider array of contexts; notably when the pages are actually rendered here on GitHub. First and foremost MyST is a Markdown standard, not a docutils one.

But thanks for the PR; optional configuration should be fine, I will try to have a look soon
