### ISSUE TITLE
First-time setup after sphinx-quickstart and sphinx-apidoc 

### ISSUE THREAD

**Issue by daniel3550** [executablebooks/MyST-Parser#340]
Hi, I'm struggling a bit with how to get started using myst in a project that already has generated RST files from sphinx-apidoc. I would like to include a README.md file in index.rst. Sorry if this is a stupid question. Do I need to convert index.rst and my other RST files to markdown to use myst? I was hoping I could make minimal changes to the project and use combination of RST and markdown.

**Comment by choldgraf** [comment]
I think that this would be a great tutorial to add for a "Getting started with MyST" section.

Short answer - no you shouldn't have to convert your rst files. If you add `myst_parser` as an extension, then Sphinx will be able to parse *both* rST and markdown

**Comment by daniel3550** [comment]
I already have an index.rst and I would like to use something like .. include directive to have the markdown rendered in index.html. I am probably thinking about this the wrong way. Should I make an index.md and use ```include``` style directive to pull the index.rst in? In that case does it matter if they are both named "index"?

**Comment by choldgraf** [comment]
Ah yes - two things - you can't have two files with the same base name even if they have two different extensions. Only one will be used. The other is that you cannot mix rst and md content in this way, so you can't include md from rst

**Comment by daniel3550** [comment]
Thanks!
