### ISSUE TITLE
Can you please document how to link to a pdf file that is stored in `_static`?

### ISSUE THREAD

**Issue by PhilipMay** [executablebooks/MyST-Parser#341]
In the documentation I am missing something about how I 
can link to a pdf file that is stored in `_static`.

Could you please add that?

Thanks
Philip

**Comment by choldgraf** [comment]
Hmmm - this one feels like it is out-of-scope for the MyST parser docs, since it is more of a base Sphinx question (here are the docs for this: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-download).

**Comment by PhilipMay** [comment]
@choldgraf thanks for the answer. The thing is that the linked solution is a rst style solution. But how do I do that with an "inline" link and MyST?

**Comment by jpmckinney** [comment]
Like this:

```
{download}`text <_static/reference.pdf>`

**Comment by PhilipMay** [comment]
Works - thanks!
