### ISSUE TITLE
MyST links to anchor links

### ISSUE THREAD

**Issue by turian** [executablebooks/MyST-Parser#356]
**Describe the bug**

Anchor links don't work.

`[Signal](../api/signal)` compiles in Sphinx but does not have an anchor link.

`[Signal](../api/signal#torchsynth.signal.Signal)` does not generate a link: "WARNING: 'myst' reference target not found: ../api/signal#torchsynth.signal.Signal"

````
```{eval-rst}
(:class:`~torchsynth.module.VCO`)`
```
````

works but creates a new paragraph

**To Reproduce**

Try to link to a particular anchor location in a particular file, e.g. above.

**Expected behavior**

There should be a way to link to MyST link to anchor locations OR an eval-rst that doesn't create a new paragraph.

**Environment**

- Python Version [e.g. 3.7.1]: 3.8.5
- Package versions or output of `jupyter-book --version`: 0.13.5 + Sphinx
- Operating System: OSX

**Comment by chrisjsewell** [comment]
Heya, I think you may be misinterpreting what anchor are here; an anchor is a link to a section header on a page (see https://myst-parser.readthedocs.io/en/latest/using/howto.html#automatically-create-targets-for-section-headers), whereas references to `autoclass` elements (I presume you have generated via apidoc) are not page specific, i.e. you could just do `[Signal](torchsynth.signal.Signal)`

Or, if you want to specifically use the `class` role instead, you can just insert this directly into the Markdown text, without using `eval-rst`: `` {class}`torchsynth.signal.Signal` ``

**Comment by chrisjsewell** [comment]
So yeh, as I've just noted in torchsynth/torchsynth#346, I think you just need to replace `:role-name:` with `{role-name}`

**Comment by turian** [comment]
@chrisjsewell wow! thank you so much for your help. We are releasing 1.0 tonight and this is great.

Is {role-name} substitution documented anyway? I am curious which doc we should refer to in the future

**Comment by chrisjsewell** [comment]
Good to hear 😄 The role syntax is detailed here: https://myst-parser.readthedocs.io/en/latest/using/syntax.html#roles-an-in-line-extension-point, but any feedback on improving this is welcome

(on a related note, I'm also finishing up https://github.com/executablebooks/rst-to-myst)

**Comment by turian** [comment]
@chrisjsewell Strange. Merging https://github.com/torchsynth/torchsynth/pull/346 removed all the git-lfs images from lgtm: https://torchsynth.readthedocs.io/en/latest/performance/batch-processing.html

but they remain in local builds. Any ideas?

**Comment by chrisjsewell** [comment]
Looks like you have some issues with the RTD build 😬 https://readthedocs.org/projects/torchsynth/builds/13602934/

<img width="924" alt="image" src="https://user-images.githubusercontent.com/2997570/116011188-0651f500-a624-11eb-903a-b4f5cd635a11.png">

**Comment by turian** [comment]
Wow! @chrisjsewell thank you.
