### ISSUE TITLE
Agree on a name for this flavor of markdown

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-Parser#39]
We have effectively invented a new flavor of markdown in this repository, one that explicitly tries to mirror the functionality of Sphinx/rST using markdownic (is that a word?) syntax. 

Thus far, the two main names we have given it are:

* Myst
* imarkdown

This is an issue to see if one of these is acceptable, or if we should keep brainstorming. I actually quite like myst, with the exception that it is a fairly popular old school video game so we might run into confusion with that in searches etc.

Other ideas

* MaST (MArkedly Structured Text)
* Spharkdown

(I don't have any other ideas I just wanted an excuse to write "spharkdown" but you all should chime in 😅)

**Comment by jstac** [comment]
Myst is pretty good, I reckon, and probably better for search engines than "MaST", despite the game.

I thought of a few more but I didn't like any as much as myst.  

Plus myst is originally from @fperez, isn't it?  That's one more vote that should be counted.

**Comment by chrisjsewell** [comment]
There should also be an associated file extension, e.g. `.myst`

**Comment by chrisjsewell** [comment]
I think we are settled on myst now
