### ISSUE TITLE
Setup.cfg specifies too low a Sphinx version 

### ISSUE THREAD

**Issue by seddonym** [executablebooks/MyST-Parser#398]
MyST-Parser is incompatible with Sphinx 3.0 (the `allowed_exceptions` argument was [introduced in Sphinx 3.1](https://www.sphinx-doc.org/en/3.x/extdev/appapi.html#emitting-events)).
 
```
sphinx-build -b html -a -E -n -W -T -v docs docs/_build'
Exit code: 2
Stdout:
    newnode = self.app.emit_firstresult(
TypeError: emit_firstresult() got an unexpected keyword argument 'allowed_exceptions'
Exception occurred:
  File "/.../.venv/lib/python3.8/site-packages/myst_parser/myst_refs.py", line 57, in run
    newnode = self.app.emit_firstresult(
TypeError: emit_firstresult() got an unexpected keyword argument 'allowed_exceptions'
```

I think the fix should just be to bump the Sphinx version number to >=3.1.

**Comment by choldgraf** [comment]
good catch, I think this would take care of it: https://github.com/executablebooks/MyST-Parser/pull/400
