### ISSUE TITLE
Hard breaks are lost in LaTeX output

### ISSUE THREAD

**Issue by cpitclaudel** [executablebooks/MyST-Parser#408]
### Describe the problem

Markdown hard breaks are lost when exporting to LaTeX, because the docutils renderer produces a `raw` HTML node.

### Steps to reproduce

Input:

```
This\
has\
hard\
breaks.

These are lost when exporting to LaTeX.
```

Output with `make latexpdf` in Sphinx:

![image](https://user-images.githubusercontent.com/8181630/127095684-cd68e05f-dee5-400a-9e09-d68fcb787e89.png)

### The version of Python you're using

3.8

### Versions of your packages

MyST: 5fd4c51

### Additional context

The faulty code is this in `docutils_renderer.py`:

```python
    def render_hardbreak(self, token: SyntaxTreeNode) -> None:
        self.current_node.append(nodes.raw("", "<br />\n", format="html"))
```

**Comment by chrisjsewell** [comment]
thanks for the feedback; do you know what the hard-break syntax in latex is?

**Comment by cpitclaudel** [comment]
`\\` is right in most cases (but not in tables; not sure how these are exported in MyST?)

**Comment by chrisjsewell** [comment]
> `\\` is right in most cases 

Ok yeh I went with adding an additional raw latex node with this.
(Its a shame that douctils AST does not have a hard-break element)

OPbviously let me know if you still have any issues in the future cheers
