### ISSUE TITLE
Could not import extension myst_parser

### ISSUE THREAD

**Issue by jasyip** [executablebooks/MyST-Parser#427]
### Describe the problem

```console
$ make html
Running Sphinx v4.2.0

Extension error:
Could not import extension myst_parser (exception: No module named 'myst_parser')
make: *** [Makefile:20: html] Error 2
```

### Link to your repository or website

https://github.com/jasyip/musescore-scraper

### Steps to reproduce

Followed steps on Quickstart Tutorial.

See my code at my repository. More specifically, https://github.com/jasyip/musescore-scraper/tree/main/docs/source

### The version of Python you're using

3.9.7

### Your operating system

Windows 11 WSL2

### Versions of your packages

* Sphinx v4.2.0
* myst-parser-0.15.2

**Comment by chrisjsewell** [comment]
Heya, perhaps you could copy here the result of running `pip list`

**Comment by jasyip** [comment]
Huh, it seems like it did not show up on `pip list`. I installed it again, then it worked. Thanks though
