### ISSUE TITLE
Configure linkify (turn off fuzzy_link)

### ISSUE THREAD

**Issue by ailin-nemui** [executablebooks/MyST-Parser#428]
### Description / Summary

I would like to turn off fuzzy_link because I have text which refers to "something.pl" and all of those get converted to links. Nevertheless I would like https:/... links to be auto-linked

### Value / benefit

It would be nice if we can configure linkify as there are several options like enabling email links etc https://linkify-it-py.readthedocs.io/en/latest/#linkifyit-schemas-options

### Implementation details

It needs a way to forward the config from conf.py -> LinkifyIt. Probably not too difficult to implement once it's clear how it should be done

**Comment by ailin-nemui** [comment]
Here is a patch that would scratch my particular itch:

```
diff -pru ./myst_parser/main.py ./myst_parser/main.py
--- ./myst_parser/main.py	2021-09-06 23:12:21.052065383 +0200
+++ ./myst_parser/main.py	2021-09-20 13:22:45.975667528 +0200
@@ -67,6 +67,7 @@ class MdParserConfig:
                 "smartquotes",
                 "replacements",
                 "linkify",
+                "linkify_nofuzzy",
                 "substitution",
                 "tasklist",
             ]
@@ -178,6 +179,8 @@ def default_parser(config: MdParserConfi
     if "linkify" in config.enable_extensions:
         # TODO warn, don't enable, if linkify-it-py not installed
         md.enable("linkify")
+    if "linkify_nofuzzy" in config.enable_extensions:
+        md.linkify.set({"fuzzy_link":False})
 
     if "dollarmath" in config.enable_extensions:
         md.use(
```

**Comment by webknjaz** [comment]
I've just faced a similar need wanting to keep a project name `Proxy.Py` as plain text. I think it'd be useful to have some sort of `linkify_exclude` option exposed to `conf.py` allowing to list things not meant to be links.

**Comment by chrisjsewell** [comment]
yeh, exposing this option makes sense 👍

Happy to accept PRs (although would add a new config option rather than as a syntax extension)

**Comment by chrisjsewell** [comment]
Ok added `myst_linkify_fuzzy_links` option.
I could add extra options at a later date, but I think this should already serve many use cases
