### ISSUE TITLE
Optional int directive option incorrectly passed as empty string, not None

### ISSUE THREAD

**Issue by zakhenry** [executablebooks/MyST-Parser#431]
### Describe the problem

I want to use the [automatic dedent](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=dedent#directive-option-code-block-dedent) feature of literalinclude:

````
```{literalInclude} path/to/my/file
---
linenos: true
lines: 19-36
lineno-match: true
dedent:
---
```
````

With the above I get the following error:

```
WARNING: Directive 'literalInclude': Invalid option value: (option: 'dedent'; value: )
invalid literal for int() with base 10: ''

---
linenos: true
lines: 19-36
lineno-match: true
dedent: 
---
```
In the Sphinx definition the test is using `None` to test the feature, see https://github.com/sphinx-doc/sphinx/pull/8684/files

however in MyST-Parser, it coerces a None value into a string:

https://github.com/executablebooks/MyST-Parser/blob/master/myst_parser/parse_directives.py#L149-L150

### Steps to reproduce

1. Using a Sphinx with MyST-Parser setup add the following code block
````
```{code-block} python
---
dedent: True
---
          print("Hello world")
```
````

2. See the following error in the console
```
 WARNING: Directive 'code-block': Invalid option value: (option: 'dedent'; value: )
invalid literal for int() with base 10: ''

---
dedent: True
---
          print("Hello world")
```

### The version of Python you're using

Python 3.9.7

### Your operating system

macOS 11.6

### Versions of your packages

Sphinx v4.2.0

**Comment by chrisjsewell** [comment]
thanks, yeh thats a pain, I will try to have a think about what the best way to handle this is
