### ISSUE TITLE
Should including code be included in docs?

### ISSUE THREAD

**Issue by andhuang-CLGX** [executablebooks/MyST-Parser#432]
### Description / Summary

I was looking at https://github.com/executablebooks/MyST-Parser/issues/204 but didn't know how to include some local code and render it.

I finally figured it out by looking at some PR:
https://github.com/executablebooks/sphinx-tomyst/pull/93/files

````
##### Title

```{literalinclude} ../path/to/some.json
---
language: json
---
```

````

### Value / benefit

Should this be added to docs?

**Comment by chrisjsewell** [comment]
Heya, thanks I guess this is related https://github.com/executablebooks/MyST-Parser/issues/81

**Comment by chrisjsewell** [comment]
I will close this then as a duplicate thanks
