### ISSUE TITLE
Headers with special symbols not seen as valid reference target

### ISSUE THREAD

**Issue by AliveDevil** [executablebooks/MyST-Parser#437]
### Describe the problem

I cannot get the myst cross reference anchors to work for headers that include either
* `/`
* `&`
* `→`

Automatic anchor-id generation does work fine, only the cross-reference (`[title](../path/to/page.md#header)`) doesn't.

### Steps to reproduce

1. Create new Sphinx-docs project with Myst-Parser
```
# conf.py
extensions = [
	"myst_parser"
]
myst_heading_anchors = 2
```
2. Create index.md document with content:
```
## Header 1
[](#header-2-with-arrow)

## Header 2 with → Arrow
[](#header-1)
```
3. Build and observe that the link in `Header 1` to `Header 2 with → Arrow` is empty.
Link to Header 1 from Header 2 works fine.

### The version of Python you're using

Python 3.8.9

### Your operating system

macOS 11 (and Windows 10, Windows 11, Github Actions Ubuntu 20.04 Runner)

### Additional context

Log output:
```
myst-links/External.md:5: WARNING: 'myst' reference target not found: #header-2-with-arrow
myst-links/External.md:7: WARNING: 'myst' reference target not found: index.md#header-2-with-arrow
myst-links/index.md:11: WARNING: 'myst' reference target not found: #header-2-with-arrow
myst-links/index.md:13: WARNING: 'myst' reference target not found: External.md#header-2-with-arrow
```

Adding a minimal sample file for reproducing: [myst-links.zip](https://github.com/executablebooks/MyST-Parser/files/7309910/myst-links.zip)

**Comment by chrisjsewell** [comment]
Heya @AliveDevil, if you run the `myst-anchors` CLI (as discussed in https://myst-parser.readthedocs.io/en/latest/syntax/optional.html?highlight=myst-anchors#auto-generated-header-anchors)

```console
$ myst-anchors test.md
<h2 id="header-1"></h2>
<h2 id="header-2-with--arrow"></h2>
```

you can see that `Header 2 with → Arrow` goes to `header-2-with--arrow`, i.e. there are two spaces replaced with two dashes 😬 
Hence, why `header-2-with-arrow` was not working

So I will close this if that's OK, but obviously any other feedback is very welcome cheers
