### ISSUE TITLE
Links with anchors don't replace `.md` with `.html`

### ISSUE THREAD

**Issue by sir4ur0n** [executablebooks/MyST-Parser#443]
### Describe the problem

If using a Markdown link without anchor:
```md
[foo](../bar.md)
```
the HTML link is:
```html
<a class="reference internal" href="../bar.html"><span class="doc std std-doc">foo</span></a>
```

However if using a Markdown link **with an anchor**:
```md
[foo](../bar.md#baz)
```
the HTML link is:
```html
<a class="reference internal" href="../bar.md#baz"><span class="doc std std-doc">foo</span></a>
```
Note that it links to `bar.md` and not `bar.html`, which is an invalid link.

### Link to your repository or website

https://haskell-language-server.readthedocs.io/en/latest/contributing/contributing.html#using-hls-on-hls-code

### Steps to reproduce

1. Create a markdown link with an anchor, e.g. `[foo](../bar.md#baz)`
2. Build the HTML documentation
3. See that the link incorrectly points to `bar.md` instead of `bar.html`

### The version of Python you're using

3.9.6

### Your operating system

NixOS 21.11pre322215.9bf75dd50b7

### Versions of your packages

```
Sphinx==4.0.2
sphinx-rtd-theme==0.5.2
myst-parser==0.15.1
docutils<0.17
```

### Additional context

I have found [a similar problem on StackOverflow](https://stackoverflow.com/questions/68744271/sphinx-docs-linking-to-specific-section-of-another-markdown-page), but the user apparently uses Recommonmark rather than MyST.

I have also found this [MyST documentation page](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#auto-generated-header-anchors) which seems to hint that the syntax `[foo](../bar.md#baz)` should work:
![image](https://user-images.githubusercontent.com/1204125/139837035-bb5134d6-6bad-4780-823f-c1d6bb58affe.png)

You can see the problem happening here: https://haskell-language-server.readthedocs.io/en/latest/contributing/contributing.html#using-hls-on-hls-code

The first link links to https://haskell-language-server.readthedocs.io/en/latest/configuration.md#configuring-your-project-build instead of https://haskell-language-server.readthedocs.io/en/latest/configuration.html#configuring-your-project-build

The source is here: https://github.com/haskell/haskell-language-server/blob/master/docs/contributing/contributing.md

**Comment by andersk** [comment]
According to the [documentation](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-header-anchors), you just need to enable this feature by configuring `myst_heading_anchors`.

**Comment by chrisjsewell** [comment]
Thanks for answering @andersk, that is indeed the correct.
So I will close this for now @sir4ur0n if thats ok, but feel free to re-open if you still encounter issues

**Comment by sir4ur0n** [comment]
Quite late: thank you all for the answers, I will give it a shot some time and get back here if I have any problem.

Thank you again :pray:
