### ISSUE TITLE
Multiline roles syntax seems broken

### ISSUE THREAD

**Issue by webknjaz** [executablebooks/MyST-Parser#448]
### Describe the problem

In a Sphinx project, I used something like this
```md
some text {ref}`some
anchor <real-ref>`
```
and it silently kept it as `{ref}` and the rest was marked as inline code.
When I put it on a single line, it actually created a clickable link.

### Steps to reproduce

`tox -e build-docs` on the https://github.com/abhinavsingh/proxy.py repo and navigate to "guidelines" document in the browser.

**Comment by john-hen** [comment]
This has been previously reported in issue #169.

**Comment by webknjaz** [comment]
Oh, so I missed that one.
