### ISSUE TITLE
Cross reference link to an autodoc function not working/documented well

### ISSUE THREAD

**Issue by asmeurer** [executablebooks/MyST-Parser#468]
### Describe the problem

Either there's no way to do this, or it isn't documented very well. I can't tell. 

I want to make a link to an autodoc function which I would normally do with 

```
{func}`~.funcname`
```

But I also want to use custom text for the link. I can't figure how to make it work. The docs [seem to imply](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#how-roles-parse-content) that it should be 

```
{func}`Text <~.funcname>`
```

but this doesn't work (that doc text is very confusing, so I can't tell if that is what it is really saying or not. IMO that whole paragraph would be much clearer if it were just replaced with an example).

I suspect this *might* be a bug, because I get an error like `WARNING: py:func reference target not found: ~.funcname` when building, even though the normal link reference works just fine.

Even if this is the right way to do it, this is not very Markdown-y IMO. My initial thing to try was 

```
[text]({func}`~.funcname`)
```

I would suggest making that work. Unfortunately, I do really need the `func` part in general to tell it what type of reference it is as `funcname` is ambiguous otherwise. Plus the default `ref` that MyST uses doesn't seem to recognize the `~.` autodoc stuff.  Otherwise I would just use `[text](~.funcname)`.

If there's some other way to do this, it isn't documented very well at all. I would suggest adding a clear "how to make a link" section to the docs. As another aside, I also found it confusing that there are two separate pages that cover the MyST syntax, with non-overlapping content. It would be nicer if everything were just on one page IMO, so I could easily search for something like "link". 

### Steps to reproduce

This is coming from the SymPy documentation (specifically I'm trying to write a reference to the `parse_latex` function there). 

### The version of Python you're using

3.8

### Your operating system

macOS

### Versions of your packages

Sphinx 4.2.0
Myst-parser 0.15.1

**Comment by chrisjsewell** [comment]
> IMO that whole paragraph would be much clearer if it were just replaced with an example

Heya, there is a section with examples on referencing: https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#targets-and-cross-referencing

Have you tried this also in .rst files: ``` :func:`Text <~.funcname>` ```, because of it doesn't then that is an upstream issue with sphinx, otherwise there should be no reason why ``` {func}`Text <~.funcname>` ``` will not work in myst files

**Comment by asmeurer** [comment]
> Heya, there is already a separate section with examples on referencing: myst-parser.readthedocs.io/en/latest/syntax/syntax.html#targets-and-cross-referencing

That section would be easier to spot if it used the more common term "link" instead of "target", which is a term only someone familiar with Sphinx or RST internals would recognize. 

Either way, my other points about the documentation stand.

**Comment by asmeurer** [comment]
> Have you tried this also in .rst files: :func:`Text <~.funcname>`, because if it doesn't then that is an upstream issue with sphinx, otherwise there should be no reason why {func}`Text <~.funcname>` will not work in myst files

Apparently the `~.` thing doesn't work inside of link even in RST. I can open an issue for that upstream.

**Comment by chrisjsewell** [comment]
Superseded by #548
