### ISSUE TITLE
0.16.1: sphinx 4.3.2 crashes on rendering MyST-Parser documentation

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-Parser#470]
### Describe the problem

Looks like sphinx 4.3.2 crashes on rendering documentation.
I've tested that sphinx 4.3.2 is OK with MyST-Parser 1.15.2 so looks like something may be wrong in latest MyST-Parser. However I have difficulty to find what exactly it is :(

More details in https://github.com/sphinx-doc/sphinx/issues/10004

### Link to your repository or website

https://github.com/sphinx-doc/sphinx/issues/10004

### Steps to reproduce

git clone https://github.com/executablebooks/MyST-Parser/
cd MyST-Parser
pip install build setuptools sphinx wheel sphinxcontrib-bibtex sphinxcontrib-mermaid sphinxext-opengraph sphinxext-rediraffe sphinx-panels
python3 -sBm build -w
python3 setup.py build_sphinx -b man --build-dir build/sphinx

### The version of Python you're using

3.8.12

### Your operating system

Linux/x86_64

**Comment by chrisjsewell** [comment]
> Looks like sphinx 4.3.2 crashes on rendering documentation.

Firstly, this is not a crash, this is one test failure, and as discussed in https://github.com/sphinx-doc/sphinx/issues/10004#issuecomment-999756623, I don't reproduce this issue.

So I will close this now, but bear it in mind if anyone else comes across a similar issue

**Comment by kloczek** [comment]
I must apologise.
I've referred to the wrong sphinx ticket :/
Here is correct on https://github.com/sphinx-doc/sphinx/issues/10003
Could you please look one more time?
