### ISSUE TITLE
toctree glob does not support files with markdown extension

### ISSUE THREAD

**Issue by arwedus** [executablebooks/MyST-Parser#471]
### Describe the problem

Assume you have the following files:

```
conf.py
index.rst
page_a.md
page_b.md
page_c.md
```

with the following directive in index.rst:

```
.. toctree::
   :maxdepth: 2
   :caption: Contents:
   :glob:

   *.md
```

You get the following messages on running `sphinx-build html`:

```
/projects/docs-as-code/toctree-example/source/index.rst:6: WARNING: toctree glob pattern '*.md' didn't match any documents
looking for now-outdated files... none found
pickling environment... done
checking consistency... /projects/docs-as-code/toctree-example/source/page_a.md: WARNING: document isn't included in any toctree
/projects/docs-as-code/toctree-example/source/page_b.md: WARNING: document isn't included in any toctree
/projects/docs-as-code/toctree-example/source/page_c.md: WARNING: document isn't included in any toctree
```

The following toctree directive would work:

```
.. toctree::
   :maxdepth: 2

   page_a.md
   page_b.md
   page_c.md
```

Is this a known limitation of sphinx?

### Steps to reproduce

I attached the example files, which you can just copy-paste in a new `sphinx-quickstart` project to reproduce (remove .txt ending):

[index.rst.txt](https://github.com/executablebooks/MyST-Parser/files/7764846/index.rst.txt)
[page_a.md](https://github.com/executablebooks/MyST-Parser/files/7764847/page_a.md)
[page_b.md](https://github.com/executablebooks/MyST-Parser/files/7764848/page_b.md)
[page_c.md](https://github.com/executablebooks/MyST-Parser/files/7764849/page_c.md)
[conf.py.txt](https://github.com/executablebooks/MyST-Parser/files/7764851/conf.py.txt)

### The version of Python you're using

3.8.9

### Your operating system

Ubuntu Linux 18.04 LTS

### Versions of your packages

```
myst-parser: 0.15.2
sphinx: 4.3.1
```

**Comment by chrisjsewell** [comment]
Glob matches against docnames, which don't include the file extension: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree

**Comment by arwedus** [comment]
@chrisjsewell : A glob of `*` adds all markdown pages indeed. I wonder why this didn't occur to me in the first place. Thanks!
