### ISSUE TITLE
headings

### ISSUE THREAD

**Issue by gempa-dirk** [executablebooks/MyST-Parser#491]
### Describe the problem

It seems that when using the sphinx extension 'myst_parser' headings written as

`# heading 1`
`## heading 2`

are not considered and formatted in HTML documents as heading and level 1 headings are not used as page titles. Are there any MyST extensions which need to be enabled to let MyST_parser correctly recognize headings? I am currently using m2r where it works.

### Link to your repository or website

https://github.com/SeisComP/seiscomp/blob/master/doc/templates/conf.py

### Steps to reproduce

1. Replace m2r with myst-parser
2. in ../doc/base/changelog.rst replace mdinclude by include
3. rebuild the package

### Versions of your packages

using sphinx in version 2.4.4

**Comment by chrisjsewell** [comment]
Heya, headings are definitely recognised, as with all commonmark syntax

> https://github.com/SeisComP/seiscomp/blob/master/doc/templates/conf.py

I note this still includes the `m2r` extension and not `myst_parser`

> in ../doc/base/changelog.rst replace mdinclude by include

As discussed in https://myst-parser.readthedocs.io/en/latest/sphinx/use.html#include-markdown-files-into-an-rst-file, you have to specify that the parser will be myst,
I suspect it is just parsing it as RST, and hence not recognizing `#` headings

> using sphinx in version 2.4.4

I'd note this is an old version of sphinx that latest myst-parser versions do not support (perhaps pip is installing an old veriosn of myst-parser?)

**Comment by gempa-dirk** [comment]
I have upgrade sphinx to 4.3.2 but the issue persists.

In the RST file the code looks like this:
```
Changelog
#########

.. include:: CHANGELOG.md
   :parser: myst_parser.sphinx_
```

and conf.py is
```
extensions = [
    # 'rst2pdf.pdfbuilder',
    'sphinx.ext.ifconfig', 'sphinx.ext.todo',
    'sphinx.ext.autodoc', 'sphinx.ext.viewcode',
    'sphinx.ext.graphviz', 'exts.numfig', 'myst_parser',
    'sphinxcontrib.bibtex']
```

but parser option is not recognized:
```
WARNING: Error in "include" directive:
unknown option: "parser".

.. include:: CHANGELOG.md
   :parser: myst_parser.sphinx_
```

from CHANGELOG.md strings like 
```
```
# Change Log

## 2022-01-04
```
are converted to text but not recognized as heading.

Writing
```
Change Log
##########

```
creates a heading as expected.

Using m2r2 instead solved the issue without re-writing the MD code.

Any recommendation on myst solcing the issue is appreciated.

**Comment by chrisjsewell** [comment]
> but parser option is not recognized:

as noted, this is only available for docutils>=0.17, what version do you have installed?

**Comment by gempa-dirk** [comment]
I cleaned the system from all docutils installations and installed in version 0.17. This makes it work. I appreciate your efforts.Thanks!

**Comment by chrisjsewell** [comment]
👍
