### ISSUE TITLE
myst-docutils-html doesn't appear to accept the myst configuration parameters or directives

### ISSUE THREAD

**Issue by tomkivlin** [executablebooks/MyST-Parser#528]
### Describe the bug

**context**
When I do `myst-docutils-html --myst-enable-extensions="html-image,colon-fence" test.md test.html`

**expectation**
I expected the HTML file to be created without any errors.

**bug**
But instead I get an error 

```
myst-docutils-html --myst-enable-extensions="html-image,colon-fence" test.md test.html
test.md:: (ERROR/3) myst configuration invalid: myst_enable_extensions not recognised: {'colon-fence', 'html-image'}
test.md:38: (ERROR/3) Unknown directive type "seealso".

test.md:27: (ERROR/3) Unknown target name: "../solution_components/platform-tcp.md".
test.md:30: (ERROR/3) Unknown target name: "#21-use-cases".
```

The original test.md file is:

````
# Reference Architecture for Infrastructure Orchestration <!-- omit in toc -->

**Document Control**:

:::{image} ../artefacts/status-wip.svg
:width: 20%
:name: status is work in progress
:align: left
:alt: status is work in progress
:::

||Document Owners|
|---|---|
|||
|||

## 2. Requirements & Use-Cases

Some text

### 2.1. Use Cases

Some text

#### 2.1.1. UC1

A blueprint for this technology stack can be found [here](../solution_components/platform-tcp.md).


However, as described in the [Use-Cases above](#21-use-cases), this architecture and the components included within need to support hardware lifecycle management for both virtualisation platforms and bare metal operating systems.

## 3. Security

Some text

### 3.3. Security Considerations

```{seealso}

Global Cyber Security Policies and Detailed Requirements must be reviewed and taken into account when creating any Solution Component or Solution Blueprints.

```
````

This is a problem as it appears that the MyST directives aren't accepted by this utility, and the command line options don't accept valid MyST extensions.

### Reproduce the bug

test.md containing:
````
# Reference Architecture for Infrastructure Orchestration <!-- omit in toc -->

**Document Control**:

:::{image} ../artefacts/status-wip.svg
:width: 20%
:name: status is work in progress
:align: left
:alt: status is work in progress
:::

||Document Owners|
|---|---|
|||
|||

## 2. Requirements & Use-Cases

Some text

### 2.1. Use Cases

Some text

#### 2.1.1. UC1

A blueprint for this technology stack can be found [here](../solution_components/platform-tcp.md).


However, as described in the [Use-Cases above](#21-use-cases), this architecture and the components included within need to support hardware lifecycle management for both virtualisation platforms and bare metal operating systems.

## 3. Security

Some text

### 3.3. Security Considerations

```{seealso}

Global Cyber Security Policies and Detailed Requirements must be reviewed and taken into account when creating any Solution Component or Solution Blueprints.

```
````

Then run the following command: `myst-docutils-html --myst-enable-extensions="html-image,colon-fence" test.md test.html`

### List your environment

Python 3.10.1
Windows 10

I am using a virtual environment and have the following packages installed:
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
attrs                         21.4.0
Babel                         2.9.1
certifi                       2021.10.8
charset-normalizer            2.0.12
colorama                      0.4.4
docutils                      0.17.1
idna                          3.3
imagesize                     1.3.0
Jinja2                        3.0.3
markdown-it-py                2.0.1
MarkupSafe                    2.1.0
mdit-py-plugins               0.3.0
mdurl                         0.1.0
myst-parser                   0.17.0
packaging                     21.3
pip                           21.2.4
Pygments                      2.11.2
pyparsing                     3.0.7
pytz                          2021.3
PyYAML                        6.0
requests                      2.27.1
setuptools                    58.1.0
snowballstemmer               2.2.0
Sphinx                        4.4.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
typing_extensions             4.1.1
urllib3                       1.26.8

**Comment by tomkivlin** [comment]
@chrisjsewell many thanks, that's really helpful.  I hadn't twigged that `seealso` was a sphinx directive - just did a quick search, so am I right in thinking the admonitions listed [here](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions) are ok to use with both MyST in sphinx and with `myst-docutils`?  

I've tried using `important` instead of `seealso` and it's worked, but wanted to check my understanding.  Thanks again.

**Comment by chrisjsewell** [comment]
> so am I right in thinking the admonitions listed [here](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions) are ok to use with both MyST in sphinx and with myst-docutils?

yep 👍

**Comment by tomkivlin** [comment]
> > so am I right in thinking the admonitions listed [here](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions) are ok to use with both MyST in sphinx and with myst-docutils?
> 
> yep 👍

Many thanks - am closing the issue as modifying the admonition and using the following command works: `myst-docutils-html --myst-enable-extensions="html_image,colon_fence" --myst-all-links-external="yes" test.md test.html`
