### ISSUE TITLE
Unable to upgrade to 0.17.0

### ISSUE THREAD

**Issue by championshuttler** [executablebooks/MyST-Parser#532]
### Describe the bug

**context**
When I upgrade from  0.16.1 to  0.17.0

**expectation**
I expected it to  succeed

**bug**
But instead it failed
Here's an error message I ran into 

```console
ERROR: Could not find a version that satisfies the requirement myst-parser==0.17.0 (from versions: 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0a1, 0.5.0, 0.5.1, 0.6.0a1, 0.6.0a2, 0.6.0a3, 0.6.0, 0.7.0, 0.7.1, 0.8.0a1, 0.8.0a2, 0.8.0a3, 0.8.0a4, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0a1, 0.14.0a2, 0.14.0a3, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1)
```

Logs - https://firefoxci.taskcluster-artifacts.net/UApS-tUoROuEQDe12BqWIA/0/public/logs/live_backing.log

### Reproduce the bug

1.  Build  log  - https://firefoxci.taskcluster-artifacts.net/UApS-tUoROuEQDe12BqWIA/0/public/logs/live_backing.log

**Comment by chrisjsewell** [comment]
Heya, it seems like you need to raise this with the software/distribution you are using to install,
since it is very definitely on https://pypi.org/project/myst-parser/0.17.0/#files, and available via `pip install`.
I guess they haven't updated their package library

**Comment by eyllanesc** [comment]
@championshuttler According to the log you are using python 3.6.9: 

```console
[task 2022-03-08T11:32:03.953Z] created virtual environment CPython3.6.9.final.0-64 in 37ms
```

But it seems that the library is available for python >=3.7:

https://github.com/executablebooks/MyST-Parser/blob/dc45a1f1f47b6b39abbb26ae2d1b50723cd06e6b/setup.cfg#L12-L26

**Comment by tora-kozic** [comment]
Hi, having the same issue here.  When pip tries to grab all the download links from Pypi, I receive the following message (running `pip install -vvv myst-parser`):

`...
Found link https://files.pythonhosted.org/packages/d9/ff/1b04d52f63f20cc8400f1f9a6cc3065e8b0bd684f14bcfe11c204eeca2a0/myst_parser-0.16.1-py3-none-any.whl#sha256=617a90ceda2162ebf81cd13ad17d879bd4f49e7fb5c4f177bb905272555a2268 (from https://pypi.org/simple/myst-parser/) (requires-python:>=3.6), version: 0.16.1
  Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/71/14/1aaf281c7deda5aff6b1b3da9dbc39660c2739ec128fcad6dad10183aa48/myst-parser-0.17.0.tar.gz#sha256=d412347a5cacb77ebc03d7f7ffef050cd61957d46f234313d350e84e24972260 (from https://pypi.org/simple/myst-parser/) (requires-python:>=3.7)
...`

Our project requirement is `>=3.7`.  Seems to me that the links for installs >0.16.1 require python version 3.6.13 (Or at least <3.6). Is this intended?

**Comment by chrisjsewell** [comment]
> require python version 3.6.13 

Heya, no this means that your current Python version is 3.6.13, which is not compatible with the requirement for python>=3.7

**Comment by chrisjsewell** [comment]
Closing this because, yeh, it appears to be related to folks having python 3.6
