### ISSUE TITLE
RFE: provide support for `docutils` 1.18.x

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-Parser#544]
### Describe the problem/need and solution

`docutils` 1.18.1 has been released and few modules started using it.
`myst-parser` still uses older version
https://github.com/executablebooks/MyST-Parser/blob/dc45a1f1f47b6b39abbb26ae2d1b50723cd06e6b/setup.cfg#L39-L40
`sphinx` already started working on new `docutils` support https://github.com/sphinx-doc/sphinx/issues/9777

**Comment by chrisjsewell** [comment]
This paclage is already tested against docutils 0.18 https://github.com/executablebooks/MyST-Parser/runs/6052519350?check_suite_focus=true, and available unpinned via https://pypi.org/project/myst-docutils/
