### ISSUE TITLE
`MdParserConfig(highlight_code_blocks=True)` doesn't produce expect HTML for code blocks

### ISSUE THREAD

**Issue by cpsievert** [executablebooks/MyST-Parser#551]
### Describe the bug

I was surprised to find that this python code doesn't produce HTML `<code>` contents suitable for use with pygments (for code highlighting). Am I missing something?

````python
from markdown_it.renderer import RendererHTML
from myst_parser.main import create_md_parser, MdParserConfig

config = MdParserConfig(highlight_code_blocks=True)
parser = create_md_parser(config, RendererHTML)
res = parser.render(
"""
# Hello world

```python
print('Hello world!')
```
"""
)

print(res)
````

```html
<h1>Hello world</h1>
<pre><code class="language-python">print('Hello world!')
</code></pre>
```

### Reproduce the bug

Run the code above with `myst_parser` 0.17.0

**Comment by chrisjsewell** [comment]
Heya, `create_md_parser` is purely the "syntax parsing" aspect of myst-parser, and primarily meant for internal use.

For "programattic parsing" check out: https://myst-parser.readthedocs.io/en/latest/docutils.html
