### ISSUE TITLE
Undocumented breaking change between 0.17.2 from 0.17.0 — myst_url_schemes

### ISSUE THREAD

**Issue by ThisIsMissEm** [executablebooks/MyST-Parser#558]
### Describe the bug

**context**
When upgrading from 0.17.0 to 0.17.2, configuration now errors out due to the warning:

```
The config value `myst_url_schemes' has type `list', defaults to `tuple'.
```

**Given** the sphinx configuration of:

```
myst_url_schemes = ['https', 'http']
```

**expectation**
I expected this change to have been documented in the CHANGELOG, such that I could understand that a breaking change was introduced.

**bug**
But instead it looked like only an internal refactor took place.

### Reproduce the bug

Use configuration of `myst_url_schemes = ['https', 'http']` for myst_parser 0.17.0, build your documentation, the build will succeed; Upgrade to 0.17.2 and the build will begin to fail, wanting `myst_url_schemes = ('https', 'http')` instead.

### List your environment

MyST_parser 0.17.2
python3.9 (I'm using sphinx-build)

**Comment by chrisjsewell** [comment]
Heya, I'd note this is not a breaking change, in that it will run perfectly fine with a list or tuple.
It was just an overlooked fact that sphinx tries to (unnecessarily in this case) enforce the same type as the default. 

I think, one could add `types=Any` here, to suppress this: https://github.com/executablebooks/MyST-Parser/blob/8854d8415528b4f61b06931f3c8e996dee3f1e2b/myst_parser/__init__.py#L40

**Comment by chrisjsewell** [comment]
See also: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_config_value

**Comment by ThisIsMissEm** [comment]
@chrisjsewell that's the thing though, it doesn't work with lists, it requires the tuple. I discovered this in https://github.com/inrupt/solid-client-notifications-js/pull/243 where our documentation builds suddenly started failing with the error:

```
The config value `myst_url_schemes' has type `list', defaults to `tuple'.
```

It's a warning that Sphinx treats as an error:
<img width="1002" alt="Screenshot 2022-04-20 at 05 31 10" src="https://user-images.githubusercontent.com/30827/164144822-aaa08ad1-2532-44ab-94b1-bdb8ba51a96d.png">

**Comment by ThisIsMissEm** [comment]
Note: the same configuration worked on 0.17.0, but as of 0.17.2, it errors out with the above.

**Comment by chrisjsewell** [comment]
> it errors out with the above.

Note, this is because you are using `sphinx-build -W`, to change warnings to errors. You might want to consider also using `sphinx-build -W --keep-going`, to not halt your build after the first warning (this is what I use)

**Comment by chrisjsewell** [comment]
Anyhow, sorted for the next release cheers
