### ISSUE TITLE
gallery.jupyterbook.org is down

### ISSUE THREAD

**Issue by llimllib** [executablebooks/MyST-Parser#604]
### Describe the bug

**context**
When I go to https://gallery.jupyterbook.org/ , which is [linked](https://github.com/executablebooks/MyST-Parser/blob/602470ebdaf81fbea999fcc0f0cf1b8e7784ec15/docs/index.md?plain=1#L100) on the front page of the MyST website

**expectation**
I expected a website to load

**bug**
But instead it doesn't

**problem**
This is a problem for people coming to your website because they can't look at a gallery of books made with MyST

I just wanted to make you aware of the issue, I didn't know where else to contact you

### Reproduce the bug

1. go to https://gallery.jupyterbook.org/

**Comment by mmcky** [comment]
@llimllib thanks for reporting. There is a gallery available 

https://executablebooks.org/en/latest/gallery.html

I'll check with `myst-parser` (cc @chrisjsewell) if we need to update that link (or if a redirect is broken on the `jupyter` docs site).

**Comment by chrisjsewell** [comment]
cheers
