### ISSUE TITLE
Possibility to include the content of a specific markdown section?

### ISSUE THREAD

**Issue by mara004** [executablebooks/MyST-Parser#628]
### Context

I'd like to include a specific section of a Readme file in my sphinx documentation. With `{include} ../../README.md` I can include the whole file, but is it also possible to include a just the content of a specific section, without the heading?

In the Readme, the first heading is the project name, while in the Sphinx documentation I would like it to be "Readme".

This is somewhat related to #516, with the difference that I'd like to rename the first heading instead of putting another heading above.

### Proposal

Something like `:section: section_name` (below the `{include}` line) to include only the content of the given section.

**Comment by mara004** [comment]
Ah, after some browsing I found the relevant code passage https://github.com/executablebooks/MyST-Parser/blob/28725fceb8e1e117cb247b06a267f82c501ce527/myst_parser/mocking.py#L319

There I realised this is already implemented with the `:start-after:` option.
However, I can't find this being documented anywhere. It would be really helpful if there were some page specifying the directive's options.

**Comment by chrisjsewell** [comment]
pr's welcome to https://myst-parser.readthedocs.io/en/latest/syntax/roles-and-directives.html#common-roles-and-directives @mara004 😄

**Comment by mara004** [comment]
Thanks, I can take a look, though usually it's best if the people who write the code also write the API documentation, to avoid mistakes or missing details. However, I also understand that developers may be busy enough with the code itself, and writing documentation can sometimes be a bit of a liability.
