### ISSUE TITLE
myst_heading_slug_func causes changes in config every time

### ISSUE THREAD

**Issue by Knaifhogg** [executablebooks/MyST-Parser#636]
### Describe the bug

**context**
When I set myst_heading_slug_func to a function, it does not share the same address the next time I run sphinx-build, which I believe causes all files to be re-run.

first run (successful build)
```console
Running Sphinx v4.3.1
loading pickled environment... done
myst v0.18.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=5, heading_slug_func=<function slugify at 0x000001C9E51E0E50>, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [config changed ('myst_heading_slug_func')] 38 added, 0 changed, 0 removed
```

second run (successful build, but fresh build)
```console
Running Sphinx v4.3.1
loading pickled environment... done
myst v0.18.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=5, heading_slug_func=<function slugify at 0x000001A5355F0E50>, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [config changed ('myst_heading_slug_func')] 38 added, 0 changed, 0 removed
```

### Reproduce the bug

1. py -m pip install python-slugify
2. in conf.py add
> from slugify import slugify

and

> myst_heading_slug_func = slugify

3. run sphinx-build

**Comment by chrisjsewell** [comment]
Heya, yeh it's a known issue that essentially you cannot pickle a function specified in the `conf.py`. 
I think perhaps if you specify the function, in a separate python file and import it, it might work 🤔

**Comment by Knaifhogg** [comment]
Is that not what I am doing in the reproduce steps? 😄 I tried making reproduce steps without a different module and then I got pickling errors, so I went with what I use myself. It builds fine, just thinks config changes when it does not.

**Comment by Alexey-NM** [comment]
It is very easy to fix, unfortanatly it is not done yet.
It happens because [add_config_value](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_config_value)
has `rebuild=true` for `myst_heading_slug_func`.
But `myst_heading_slug_func` is a function and it connot be saved. So when sphinx load previous config it will get empyt value for `myst_heading_slug_func`  and consider it as changes in config because current value fo `myst_heading_slug_func` will be not empty. 

We have written following hack to overcome it in `config.py`:
```
def setup(app:sphinx.application.Sphinx):
    app.config.values['myst_heading_slug_func']=(None, '', typing.Any)
    app.connect('missing-reference', gs_conf.missing_reference)      
```

**Comment by Knaifhogg** [comment]
Thank you for this bypass. I updated my conf.py with
```
import sphinx
import typing

def setup(app:sphinx.application.Sphinx):
    app.config.values['myst_heading_slug_func']=(None, '', typing.Any)
```

and now when I edit one file I get:

> building [html]: targets for 1 source files that are out of date
> updating environment: 0 added, 1 changed, 0 removed

as expected. Great!
