### ISSUE TITLE
Myst don't respect YAML

### ISSUE THREAD

**Issue by Freed-Wu** [executablebooks/MyST-Parser#638]
### Describe the bug

```markdown
---
title: H1
---

## H2
```

`make -Cdocs html` will treat H2 as H1 and don't understand H1.

### Reproduce the bug

As above.

**Comment by chrisjsewell** [comment]
Heya, you need to set `myst_title_to_header = True`: https://myst-parser.readthedocs.io/en/latest/configuration.html#global-configuration
