### ISSUE TITLE
Including documents is broken (inside and outside the source folder, e.g. ../../README.md)

### ISSUE THREAD

**Issue by bwulff** [executablebooks/MyST-Parser#647]
### Describe the bug

**context**
I followed the instructions in the documentation on how to [include a markdown file (that is outside of the source folder).](https://myst-parser.readthedocs.io/en/latest/faq/index.html?highlight=readme#include-a-file-from-outside-the-docs-folder-like-readme-md)

**expectation**
I expected to see the content of that file showing up in the rendered documentation at the place where the include statement is in the rst file (my case index.rst).

**bug**
In the rendered documentation there is the include statement as a code block. This happens not only for files outside of the source dir, include of md files that are in `/doc/source/` also fails. I also tried `{literalinclude}` with the same result.

![screenshot of the bug](https://github.com/bwulff/dummy_for_myst_parser/raw/master/images/bug.png)

```console
$ git clone https://github.com/bwulff/dummy_for_myst_parser.git dummy
$ cd dummy/doc
$ make html
```

**problem**
This is a problem because the scenario of including the content of the README.md in the documentation is a very common use case. Another use case would be to include the output of `pip-licenses` (which is produces just the table so you need to embed it into a page with a heading to make it being recognized in Sphinx build).

### Reproduce the bug

I have created a minimal Python project and used `sphinx-quickstart` to create the stub of the documentation. Then I changed the configuration (`source/config.py`) to include MyST. The bug can be recreated using the steps below:

```console
$ git clone https://github.com/bwulff/dummy_for_myst_parser.git dummy
$ cd dummy/doc
$ make html
```

### List your environment

OS: Debian 11 (bullseye) (as Docker-Image: python:3.8)
Python 3.8.13
Output of `pip freeze`:
```
alabaster==0.7.12
astroid==2.12.12
autoclasstoc==1.5.2
Babel==2.11.0
certifi==2022.9.24
charset-normalizer==2.1.1
docutils==0.17.1
idna==3.4
imagesize==1.4.1
importlib-metadata==5.0.0
Jinja2==3.1.2
lazy-object-proxy==1.8.0
linkify-it-py==2.0.0
markdown-it-py==2.1.0
MarkupSafe==2.1.1
mdit-py-plugins==0.3.1
mdurl==0.1.2
more-itertools==9.0.0
myst-parser==0.18.1
numpydoc==1.5.0
packaging==21.3
pip-licenses==4.0.1
prettytable==3.5.0
Pygments==2.13.0
pyparsing==3.0.9
pytz==2022.6
PyYAML==6.0
requests==2.28.1
snowballstemmer==2.2.0
Sphinx==5.3.0
sphinx-autoapi==2.0.0
sphinx-rtd-theme==1.1.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-confluencebuilder==1.9.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
typing_extensions==4.4.0
uc-micro-py==1.0.1
Unidecode==1.3.6
urllib3==1.26.12
wcwidth==0.2.5
wrapt==1.14.1
zipp==3.10.0
```

**Comment by chrisjsewell** [comment]
Heya, these instructions are for including a markdown file inside another markdown file, not an rst file

**Comment by chrisjsewell** [comment]
You need to read: https://myst-parser.readthedocs.io/en/latest/faq/index.html?highlight=readme#include-markdown-files-into-an-rst-file
