### ISSUE TITLE
Inline include's don't work as expected

### ISSUE THREAD

**Issue by jacobtomlinson** [executablebooks/MyST-Parser#649]
### Describe the bug

**context**
I tried to use an include in the ``` {include}`path/to/file.md` ``` format today out of the habit of using other directives but I see an error which suggests this isn't implemented.

```
ERROR: Unknown interpreted text role "include".
```

Switching to the documented code fence format works fine but the additional newline feels unnecessarily verbose.

````
```{include} path/to/file.md 
```
````

It would be nice if the shorthand version works as well.

### List your environment

```
$ conda list | grep myst                 
myst-nb                   0.17.1             pyhd8ed1ab_0    conda-forge
myst-parser               0.18.1             pyhd8ed1ab_0    conda-forge

$ conda list | grep cpython         
python                    3.9.13          h9a8a25e_0_cpython    conda-forge

$ head -n2 /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

**Comment by chrisjsewell** [comment]
> It would be nice if the shorthand version works as well.

Heya @jacobtomlinson roles are not shorthand for directives, and you can't use them interchangeably; one is used as an inline extension point, and the latter is a block level extension point.

 Sphinx has no built-in `include` role, hence neither does myst-parser: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#roles

You would need to add this in sphinx, or create your own sphinx extension for this
