### ISSUE TITLE
Recommend doc role instead of [](doc.md)

### ISSUE THREAD

**Issue by mgielda** [executablebooks/MyST-Parser#697]
### Context

In the final note, https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#targets-and-cross-referencing suggests that if you want to link to a chapter and just use the chapter's name, you can simply do `[](chapter-file.md)`. However, this is not really recognized as valid markdown anywhere I'd seen outside if MyST, including GitHub and GitLab.

I haven't drilled down in to the markdown spec as such too much, but it does look like this is non-standard syntax outside the spec. It's not that rst does not have a solution for this - it's the {doc} role which does exactly what's needed: {doc}`chapter-file` renders as the chapter name, and in other renderers (GH, GL) at least it shows up in the text at all.

While {ref} is mentioned in the text, {doc} isn't. Is there a reason?

### Proposal

I think it makes sense recommend using {doc}`sth` and discourage `[](sth.md)` in the official docs. Otherwise we're pushing people to use syntax that is neither valid md nor rST.

### Tasks and updates

- [ ] discuss if there are any counterarguments
- [ ] update documentation

**Comment by mgielda** [comment]
Heh, I literally had to edit my own issue so that the non-standard syntax would show up, which kinda proves the point.

**Comment by chrisjsewell** [comment]
Heya,

> I haven't drilled down in to the markdown spec as such too much, 

The CommonMark spec, does stipulate anything for cross-document referencing

> However, this is not really recognized as valid markdown anywhere I'd seen outside if MyST, including GitHub and GitLab.

Yes it is supported by GitHub, for example, go to https://github.com/executablebooks/MyST-Parser/blob/master/example-include.md, and click on the top link, which is written as `[Used in how-to](docs/faq/index.md)`

Its also supported in VS Code: https://code.visualstudio.com/docs/languages/markdown#_drag-and-drop-to-insert-links-and-images

`{doc}sth`, on the other hand is not supported anywhere outside of MyST

**Comment by chrisjsewell** [comment]
> I think it makes sense recommend using `` {doc}`sth` `` and discourage `[](sth.md)` in the official docs. 

We are going in exactly the opposite direction, to make it possible to always use "pure" Markdown links for referencing, and not have to use the bespoke and limiting (e.g. no nested parsing) roles syntax.

So I'm afraid this will not happen

**Comment by mgielda** [comment]
@chrisjsewell I think you misread my comment entirely. I am only talking about links with an *empty* title. `[Used in how-to](docs/faq/index.md)` is perfectly valid but `[](docs/faq/index.md)` is not.

**Comment by mgielda** [comment]
Let me illustrate this: 

[Used in how-to](docs/faq/index.md) is perfectly valid but [](docs/faq/index.md) is not.

**Comment by chrisjsewell** [comment]
> I am only talking about links with an empty title

Ok fair 👍, but still I think this is a niche case, that it is not worth confusing users with introducing roles etc, and in general I would say it's usually better to provide explicit text.

Its not that it is non-valid markdown, it is perfectly valid within the spec. It is just that most Markdown renderers treat this as converting to an `<a href="link"><a>` with no content, so its there but you just don't see it.

It's kind of on the roadmap, to allow for using a `doc` (or equivalent name) schema, i.e. then you could use an auto-link `<doc:docs/faq/index.md>`, which is more consistent with Markdown syntax.

**Comment by chrisjsewell** [comment]
> ... is perfectly valid but is not.

and yeh just to emphasise, this is what HTML is actually produced by GitHub

![image](https://user-images.githubusercontent.com/2997570/218093004-6d7cb0c6-4c4f-49cb-9cdf-30fbaef6eaeb.png)

**Comment by mgielda** [comment]
Point taken. It's valid but does not show up in what the user sees due to the link name being empty (which still I believe represents undesired behavior). Anyway I assumed since {ref} is supported, {doc} sounds like a sensible recommendation given that it just works. Of course if you add more possibilities through the autolinks syntax, that's also cool. But I would still think `[](name.md)` is worse than {doc}`name.md`, given that the latter does render and works today in Sphinx.

I will not die on that hill of course ;-)

**Comment by chrisjsewell** [comment]
Yeh no worries, obviously you are completely welcome to use `{doc}`, it will be going in the documentation though.

There should be one clear way/syntax of doing things, Markdown link/auto-link syntax is that way, so improvements should be made to that, not regressing to roles

**Comment by mgielda** [comment]
I guess I just didn't know roles were considered a "regression". I thought the major value proposition of MyST was enabling rst-like roles and directives which play nice with Sphinx and make it easy for people to transition from rst, rather than becoming yet another flavor of Markdown. Don't get me wrong, my remark wasn't meant to influence the direction of the project, I just assumed roles were considered a primary citizen. I may have missed this change of direction (or maybe missed that it was never meant to be a long-term commitment), and of course it makes me sad but I didn't want to *complain*, sorry if that's how you received it. I thought I'd made a useful observation of how to get people to use a syntax I thought was both 100% native to MyST and worked in other places.

**Comment by chrisjsewell** [comment]
>  I didn't want to complain, sorry if that's how you received it

Oh no not all 😄  I appreciate the feedback, I just wanted to give a clear/honest response.

The proposition hasn't changed: MyST add roles and directives as *extension* points, to extend the core syntax of Markdown.
But, Markdown already has a core syntax for references, one that is better than RST/sphinx in most ways.
On this point, I would even note that `doc`, `ref`, etc are not even "core rst", because they are added by sphinx and not part of docutils core implementation.

Given people one clear way to write references, that they probably already know; `[...](...)`, `<...>`, etc, is much better

> make it easy for people to transition from rst

It is certainly written with this in mind, although obviously we would prefer that just wrote in MyST from the start and didn't have to transition. Then, to that end, people should not have to "learn rst" before they can write MyST

**Comment by mgielda** [comment]
Happy to use `<doc:docs/faq/index.md>` when it's there ;-)

Closing this one then.
