### ISSUE TITLE
New release with relaxed sphinx constraints

### ISSUE THREAD

**Issue by s0undt3ch** [executablebooks/MyST-Parser#700]
### Context

I'm after a new release of myst-parser with the relaxed sphinx constrains.

Right now, the current release does not allow Sphinx >= 6.0 to be used.

### Proposal

Cut a release with the relaxed constrains and whatever was necessary to make it work with Sphinx >= 6.0

**Comment by cberthiaume** [comment]
Related conversation about Sphinx 6 support seems to be [here](https://github.com/executablebooks/MyST-Parser/pull/664).

**Comment by chrisjsewell** [comment]
Check out the new documentation: https://myst-parser--717.org.readthedocs.build/en/717/
A release is close 😅

**Comment by chrisjsewell** [comment]
Job done 🎉
