### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by barrelful** [executablebooks/MyST-Parser#710]
### Context

I see many improvements were made in the library and also support for newer Sphinx.

### Proposal

Would be excellent if you can release a new version.

**Comment by chrisjsewell** [comment]
Just keeps ne people waiting so they appreciate it more 😅

But no it will be soon, with lots of improvements

**Comment by pablo-de-andres** [comment]
I was currently updating dependencies in my docs, and got a conflict because `myst-parser 0.18.1 depends on sphinx<6 and >=4`. 
Sphinx `6.1.3` is out, and I see the main branch would support it. So +1 :)

**Comment by staticdev** [comment]
@chrisjsewell just to avoid headaches and new issues, I always avoid capping max versions of dependencies unless I am very sure it will not work. This also minimizes overhead communication of each new version launched. In your case I would just change:

https://github.com/executablebooks/MyST-Parser/blob/master/pyproject.toml#L42

to "sphinx>=5"

There is an extensive article with ideas related to that just in case: https://iscinumpy.dev/post/bound-version-constraints/

**Comment by chrisjsewell** [comment]
> I always avoid capping max versions of dependencies unless I am very sure it will not work. 

I am very sure it will not work

**Comment by chrisjsewell** [comment]
> There is an extensive article with ideas related to that just in case: [iscinumpy.dev/post/bound-version-constraints](https://iscinumpy.dev/post/bound-version-constraints/)

![image](https://user-images.githubusercontent.com/2997570/220452316-94304570-5742-4eb7-b296-1b4ef904c948.png)

**Comment by staticdev** [comment]
@chrisjsewell you have a good point but unfortunately almost everyone is using poetry nowadays, and poetry does not ignore that. And by very sure I would say, there is an available release of sphinx 7 (which wasn't in last 5 min) and you tested against latest code and does not work. But this is just a suggestion of course, you know your project better than me for sure and you read it then =)

**Comment by barrelful** [comment]
> Just keeping people waiting so they appreciate it more sweat_smile
> 
> But no it will be soon, with lots of improvements

Hunger is the best spice.

**Comment by chrisjsewell** [comment]
FYI, this is basically where I wanted to get to 😅 https://myst-parser--717.org.readthedocs.build/en/717/
If you look through the authoring sections, lots of nice improvements 👌

**Comment by staticdev** [comment]
It looks excellent, great job!

**Comment by mgielda** [comment]
I can only +1 here :) we are adopting many of the new syntactic solutions, and the myst-example directive is super nice for showing off cool MyST tricks!

**Comment by chrisjsewell** [comment]
Its here boys and girls 🎉
