### ISSUE TITLE
`attrs_block` support for name attribute

### ISSUE THREAD

**Issue by Sporiff** [executablebooks/MyST-Parser#726]
### Context

#703 introduced a really helpful extension which makes writing code blocks a lot simpler. In the majority of cases, being able to specify the `linenos` and `emphasize-lines` parameters is sufficient for smaller blocks. The only other thing I find myself needing to do frequently is name the blocks.

For context: I work on a project where we document a lot of duplicate classes/functions across a number of platforms. I use the code block name to generate tooltips for hovering over function names in the document and show the invocation as it is in the code.

My team has indicated that using the standard ```{language} invocation for code blocks makes their lives a lot simpler than needing to remember the `{code-block}` directive and additional parameters inside the block, and that the syntax using the `attrs_block` is more readable to them in the source document than something with nested parameters. If possible, I'd like to be able to fully replace the `{code-block}` invocation in my project since we use very few of Sphinx's other features for these blocks.

### Proposal

If possible, I'd like to be able to use the new functionality introduced in the `attrs_block` plugin to replace the following syntax:

````
```{code-block} java
:name: android-method1

public void method1 (boolean argument)
```
````

With something like this:

````
{name="android-method1"}
```java
public void method1 (boolean argument)
```
````

**Comment by chrisjsewell** [comment]
Hey @Sporiff thanks, and you should be able to already!

For all uses of attrs_block `#name` specifies the id (aka name) and the `.class` specifies classes, e.g.

````markdown
{#name .class1 .class2}
```python
hallo = "world"
```
````

give it a go and let me know if that works for you 😄

**Comment by Sporiff** [comment]
Hi @chrisjsewell that works perfectly! Chalk it up to my lack of reading comprehension 😜 

I think this plugin will make our lives a lot easier. Thank you for all you do!

**Comment by chrisjsewell** [comment]
No worries! Obviously if you think the documentation could be improved then let me know! (although check out #717 first)
