### ISSUE TITLE
0.19 bug with Intersphinx / objects.inv?

### ISSUE THREAD

**Issue by benjaoming** [executablebooks/MyST-Parser#731]
### Describe the bug

**context**

I'm fixing up some Intersphinx references on docs.readthedocs.io after the latest release. That's all good and anticipated, a couple have been fixed and work now. But there are two references that seem to have broken but I don't see that the docs have changed...

Here is what we had before that seemed to work - you can see the 2 links that have rendered correctly here in our latest successful build: https://docs.readthedocs.io/en/stable/guides/migrate-rest-myst.html#how-to-write-your-content-both-in-restructuredtext-and-myst

Here is one of those links:

```
{ref}``install the `myst-parser` Python package <myst-parser:intro.md#installation>``
```

It points of course here: https://myst-parser.readthedocs.io/en/latest/intro.html#installation

I then refer to the changelog and noticed the new link syntax:

https://myst-parser.readthedocs.io/en/stable/develop/_changelog.html#extended-markdown-links

I've tried to update to 0.19 and using the new syntax:

```
[install the `myst-parser` Python package](myst-parser:intro.md#installation)
```

... I get:

```
sphinx.errors.SphinxWarning: readthedocs.org/docs/user/guides/migrate-rest-myst.md:29:'myst' cross-reference target not found: 'myst-parser:intro.md#installation' [myst.xref_missing]
```

Then I tried to look at [objects.inv](https://myst-parser.readthedocs.io/en/stable/objects.inv) and searched for lines containing "intro", it's only these:

```
intro std:doc -1 intro.html 🚀 Get Started
intro/get-started std:label -1 intro.html#intro-get-started 🚀 Get Started
intro/reference std:label -1 intro.html#intro-reference Cross-referencing
intro/sphinx std:label -1 intro.html#intro-sphinx Enable MyST in Sphinx
intro/writing std:label -1 intro.html#intro-writing Write a Markdown document
```

Being new to MyST, I'm a bit confused about what's going on. I tried running myst-parser 0.18.1 and 0.19, but it could seem that the problem perhaps is with the generated objects.inv.

### Reproduce the bug

Add myst-parser as an Intersphinx inventory, then use a link like this:

```
[install the myst-parser Python package](myst-parser:intro.md#installation)
```

See that it fails and that it's not actually in the objects.inv

**Comment by chrisjsewell** [comment]
Heya, See https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#cross-project-intersphinx-links

```
[install the myst-parser Python package](inv:myst-parser:intro.md#installation)
```

**Comment by chrisjsewell** [comment]
Well actually that's maybe not quite right, but yeh readthedocs (pun intended) and let me know if it's still not clear

**Comment by benjaoming** [comment]
Nay, no luck. I think this variant should be possible too, but it should be the same as writing `intersphinx_mapping_name:ref#label`, no?

Error is the same:

```
docs/user/guides/migrate-rest-myst.md:29:No matches for 'myst-parser:intro.md:*:installation' [myst.iref_missing]
```

The error looks like the former error. I think it looks like the reference is understood correctly, but it doesn't resolve.

Our intersphinx mapping is unchanged:

https://github.com/readthedocs/readthedocs.org/blob/main/docs/conf.py#L91

**Comment by benjaoming** [comment]
```
$ pip freeze|grep myst-parser
myst-parser==0.19.0
```

**Comment by chrisjsewell** [comment]
just run: `myst-inv "https://myst-parser.readthedocs.io/en/latest/" > myst-parser.yaml` and you can see all the references.
`installation` is not there 😅

**Comment by benjaoming** [comment]
So you mean you can confirm the issue, right? :)

I was using `sphobjinv`, was something inaccurate in my output?

**Comment by chrisjsewell** [comment]
So yeh you don't need to use `sphobjinv`, `myst-inv` is better 😉 

But basically, if you look in: `myst-inv "https://myst-parser.readthedocs.io/en/v0.18.1/" > myst-parser.yaml`
You will indeed find references like `intro.md#installation`, HOWEVER....
This was essentially a bug 🙈 (or at least unintentional)
Those references are from "implicit" (auto-generated) heading anchors, which were really not intended to be in the `objects.inv`, as opposed to explicit reference targets, like:

```markdown
(target)=
# my heading
```

**Comment by chrisjsewell** [comment]
The problem with allowing others to externally reference these kinds of targets, i.e. based on the filename + heading text, is that they are very likely to change with any changes in the documentation

**Comment by benjaoming** [comment]
> The problem with allowing others to externally reference these kinds of targets

But if the anchor exists and is published (`intro.html#installation`), then it's also explicit and exposed for the entire internet to link to?

What I mean is that https://myst-parser.readthedocs.io/en/stable/intro.html#installation is still a valid URL target regardless of whether the Sphinx reference doesn't exist.

But I agree, it's much better to write down explicit labels that aren't changed every time that the headline changes.

**Comment by chrisjsewell** [comment]
I'm not inclined to add these back though I'm afraid.
Not unless there is a particularly large consensus of people that wanted it.
Have to chalk that on down to bad luck. Most of these would have probably changed since 0.18 anyway, and there should be explicit links for most sections, but let me know if you need any others added for particular locations

**Comment by benjaoming** [comment]
Yes, I agree on adding explicit Sphinx labels, that's great! But then the problem remains that implicit anchor links are auto-generated and will still be public references that StackOverflow etc. might refer to.

For instance:

```
(intro/reference)=
## Cross-referencing
```

Is still auto-generated differently:

```
https://myst-parser.readthedocs.io/en/stable/intro.html#cross-referencing
```

Now, I'd have to go back and look at how vanilla Sphinx does this, can't remember :)

**Comment by chrisjsewell** [comment]
> Now, I'd have to go back and look at how vanilla Sphinx does this, can't remembe

Pretty sure it doesn't do anything.
But anyhow if you wanted to use the standard URL links, then why not use the without intersphinx.
I'd note, I do have sphinx.rediraffe setup to redirect from old pages, so old urls should at least link to the right page

**Comment by chrisjsewell** [comment]
(https://github.com/wpilibsuite/sphinxext-rediraffe)

**Comment by benjaoming** [comment]
That former input wasn't really about my own use case, it was more to say that you cannot simply remove the implicit Sphinx/MyST ref generation from headlines and be done... there are still anchor links that are auto-generated :)

It seems that docutils have written about it here, but I find it rather cryptic: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#explicit-hyperlink-targets

So because I don't understand what the docs are trying to say, I looked at our RTD usage of `autosectionlabel` and it does the following:

1) If you *do not* specify any explicit label, it will generate `slug-name` for both the Sphinx and the URL anchor `#slug-name`.
2) If you specify an explicit name, then the Sphinx label is set to `explicit-name` but the URL is still for example `#auto-generated-headline` :exploding_head: 

If there are any name clashes, I think the second occurrence of the same headline name seems to become `#id123`.

I think that both Sphinx and MyST should be creating the same consistent and explicit `#sphinx-label-id` for the URL anchor and not `#auto-generated-slug-from-headline`. I'm inclined to say that `#id123` is so wrong that it should just raise a warning to add an explicit target label.

It feels likely that someone has described this issue for docutils or Sphinx, just haven't looked in the issue trackers.

> But anyhow if you wanted to use the standard URL links, then why not use the without intersphinx.

For my use case, I have options:

1) Contact maintainers of myst-parser and ask to have an explicit Sphinx label so I can use Intersphinx -- no one will do that, and I don't think that you should be editing your documentation to add explicit target labels to cater for other documentation sets :)

2) We can use the direct URL https://myst-parser.readthedocs.io/en/stable/intro.html#installation

3) Don't link to the section but have a more robust intersphinx reference simply to https://myst-parser.readthedocs.io/en/stable/intro.html using the `:doc:` role.

We went with 2), but 3) is also fine for me.

**Comment by benjaoming** [comment]
No no, I understand it. I tried to separate out the concern for URL anchors from docutils/sphinx/myst target labels.

But it seems like the MyST docs now use only explicit target labels and therefore the previous implicit `intro.md#installation` label is gone. Like, it worked before, so I'm guessing from your explanation that you're fine with the new behavior.
