### ISSUE TITLE
Internal target references with multiple numbers not found

### ISSUE THREAD

**Issue by alissa-huskey** [executablebooks/MyST-Parser#750]
### Describe the bug

**context**
* When I have `myst_heading_anchors: 5` in my `_config.yml`
* and I have a heading title like `## Part 4.5: Some Important Step`.
* and I attempt to reference the header using the syntax `[Don't forget!](#part-4-5-some-important-step)`

**expectation**
I expected the text `"Don't forget!"` to link to the heading `"Part 4.5: Some Important Step"` in the same document.

**bug**
But instead the target is not found.

Here's an error message I ran into...

```console
./docs/internal-target-ref.md:12: WARNING: 'myst' reference target not found: #part-4-5-some-important-step
```

**problem**
This is a problem for people because it makes internal references for headers of this type very difficult.

### Reproduce the bug

1. Go to the [Live Preview](https://myst-parser.readthedocs.io/en/latest/live-preview.html)
2. Paste in the following **working** markdown:
    ```markdown
    # Internal Target Reference Working Example

    ## Part 4: The header

    This section is for the auto-slug header we will try to reference.

    ## Part 5: The Reference

    [This](#part-4-the-header) is where we reference the internal target.
    ```
3. Now paste the following with with the header (and reference) changed from `"Part 4: ..."` to `"Part 4.4: ..."` to see the **error** behavior:
    ```markdown
    # Internal Target Reference Bug

    ## Part 4.4: The header

    This section is for the auto-slug header we will try to reference.

    ## Part 5: The Reference

    [This](#part-4-4-the-header) is where we reference the internal target.
    ```
4. If you use developer tools in a web browser to inspect the header element, you can confirm that the target is rendered as expected in the HTML. You can paste the `href` value onto the end of the URL and it will also work as expected. It is just the cross-referencing that is not working.
    ```html
    <h2>Part 4.4: The header<a class="headerlink" href="#part-4-4-the-header" title="Permalink to this heading">#</a></h2>
    ```

### List your environment

```console
> jupyter-book --version
Jupyter Book      : 0.15.1
External ToC      : 0.3.1
MyST-Parser       : 0.18.1
MyST-NB           : 0.17.1
Sphinx Book Theme : 1.0.0
Jupyter-Cache     : 0.5.0
NbClient          : 0.5.13
```

```console
> python --version
Python 3.8.16
```

```console
> uname -a
Darwin jabberwockey 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64 arm Darwin
```

The relevant part of my `_config.yml`:
```yaml
parse: &parse
  myst_heading_anchors      : 5
```

**Comment by chrisjsewell** [comment]
Hey @alissa-huskey,

you are using the not quite the right link, this works:

```
# hey
## Part 4.5: Some Important Step

[hi](#part-45-some-important-step)
```

As specified in: https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets

> The anchor “slugs” are created according to the [GitHub implementation](https://github.com/Flet/github-slugger): heading titles are lower cased, punctuation is removed, spaces are replaced with -, and uniqueness is enforced by suffix enumeration.

Critically here: **punctuation is removed**, not replaced by `-`

You can also use the `myst-anchors` CLI to view the implicitly generated targets: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#inspect-the-links-that-will-be-created

> If you use developer tools in a web browser to inspect the header element

docutils, and thus myst-parser, does not "guarantee" the generated HTML `id`, only that references will correctly link with references, according to the spec for ids

**Comment by chrisjsewell** [comment]
(happy to recieve PRs, if you feel that the documentation is not clear enough 😄 )
