### ISSUE TITLE
mst parser will remove an entire table from a document if you have an extra comma in the table text

### ISSUE THREAD

**Issue by lwasser** [executablebooks/MyST-Parser#751]
### Describe the bug

**context**
When I create a csv-table item as in the item below it works well! 

````
```{csv-table}
:header: Feature, PDM, Notes
:widths: 20,5,50

Use Other Build Backends, ✅, When you setup PDM it allows you to select from Hatch; PDM-517 and PDM-core build tools. PDM also can work with Meson-Python which supports move complex python builds.
```
````

**expectation**
I expect it to render the table and it does. 

**bug**
However, if i do this: (notice here there is a comma in the sentence "When you setup pdm, "

```{csv-table}
:header: Feature, PDM, Notes
:widths: 20,5,50

Use Other Build Backends, ✅, When you setup PDM, it allows you to select from Hatch; PDM-517 and PDM-core build tools. PDM also can work with Meson-Python which supports move complex python builds.
```

**problem**
The table simply disappears! it took me a while to figure out why the table was disappearing but now i know. Is there some way to "escape" commas that are in text? or is this a bug (or user error!)

many thanks! i love using MyST and use it almost daily now. 

### Reproduce the bug

```{csv-table}
:header: Feature, PDM, Notes
:widths: 20,5,50

Use Other Build Backends, ✅, When you setup PDM, it allows you to select from Hatch; PDM-517 and PDM-core build tools. PDM also can work with Meson-Python which supports move complex python builds.
```

### List your environment

i am using a nox environment - so i'm not sure how to access the packages it is using within that environment. i'm happy to add if you provide instructions (assuming this is a bug and not leah-error)!!

**Comment by agoose77** [comment]
Hi @lwasser, thanks for filing a report! Perhaps you could explain what you would like the final table to look like in your example? `csv-table` is supposed to treat the body as a CSV table; each row is a new line, and each column is delimited by a comma. In this case, your example sentence forms four columns, but you only supply three headers. 

From your example, I think you already know this, so I'm just stating it for posterity.

You can provide an `escape` option to the directive which allows you to escape the internal commas, e.g.:
```markdown
{csv-table}
:header: Feature, PDM, Notes
:widths: 20,5,50
:escape: "@"

Use Other Build Backends, ✅, When you setup PDM@, it allows you to select from Hatch; PDM-517 and PDM-core build tools. PDM also can work with Meson-Python which supports move complex python builds.
```

More useful, however, is probably the `delim` parameter:
```markdown
{csv-table}
:header: Feature, PDM, Notes
:widths: 20,5,50
:delim: "|"

Use Other Build Backends | ✅ | When you setup PDM, it allows you to select from Hatch; PDM-517 and PDM-core build tools. PDM also can work with Meson-Python which supports move complex python builds.
```

Hopefully these parameters help your use case! Let me know if not, and we can discuss further :)

**Comment by lwasser** [comment]
@agoose77  i'm so sorry i wasn't seeing those delimeter / escape options originally in the docs!! But they are there and I see them now. 

THANK YOU SO MUCH. i'm certain that will fix things. I almost opened this in a discussion wondering if it was leah-error and now know that I should have. Many thanks for the speedy reply (and again for the work being done here)!! closing!
