### ISSUE TITLE
sphinx 7

### ISSUE THREAD

**Issue by MehdiChinoune** [executablebooks/MyST-Parser#762]
### Context

myst-parser doesn't support sphinx>=7

**Comment by mgorny** [comment]
Ping.

**Comment by staticdev** [comment]
@chrisjsewell I propose to remove this upper bound limit to this library for sphinx here https://github.com/executablebooks/MyST-Parser/blob/master/pyproject.toml#L42. This will create less spam for you when a new major version happens (it will, of course, happen in case something really breaks).

**Comment by nejch** [comment]
If you find the time, I think it would make sense to publish a small release to also propagate this change to users on pypi :bow: sorry for the noise.
