### ISSUE TITLE
`(p)` not converted though `"replacements"` added to `myst_enable_extensions`

### ISSUE THREAD

**Issue by dbitouze** [executablebooks/MyST-Parser#807]
### Describe the gap in the current documentation

At https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#typography page, the documentation reads that, with `"replacements"` added to `myst_enable_extensions`, the text `(p)` should be automatically converted (4<sup>th</sup> row of the table). But, AFAICS with both Firefox and Chromium on GNU/Linux, that's not the case: it results just in “(p)”.

**Comment by chrisjsewell** [comment]
Yep was removed in the newer versions: https://github.com/executablebooks/markdown-it-py/commit/dd51f6222ed5e93ecfcf4514f67c71be99430011
