### ISSUE TITLE
Add support for the keys "target" and "rel" in inline_attrs 

### ISSUE THREAD

**Issue by JonZeolla** [executablebooks/MyST-Parser#820]
### Describe the feature you'd like to request

I would like to be able to create a link that, when clicked, opens in a new tab.

I found that [in the documentation](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-attributes), "only certain key-value attributes are supported for each syntax".

### Describe the solution you'd like

I would like `[here](example.md){target="_blank" rel="noreferer noopener"}` to work.

### Describe alternatives you've considered

My workaround is to directly use `<a href="example.html" target="_blank" rel="noreferer noopener">`

**Comment by lsteeger** [comment]
Using: myst-parser 3.0.1

While the implementation of **myst_links_external_new_tab = True** addresses _external_ links, it does not address
the OP's request.

```
[here](example.md){target="_blank" rel="noreferer noopener"}
```

The OP enhancement request has not really been addressed for an _internal_ link reference.

Please re-open this issue and consider expanding support to _all_ link types.
