### ISSUE TITLE
configuration via `pyproject`

### ISSUE THREAD

**Issue by pascal456** [executablebooks/MyST-Parser#827]
### Describe the feature you'd like to request

Configuration via `pyproject.toml`

For research projects we use Python most of the times. Currently we are setting up documentation and also experiment presentation with notebooks. To be precise, we agreed on a _configure as little as much_ approach. And myst Markdown and parser and notebooks solve this very nicely.

It would be nice if we could do the configuration of Myst in the file that we use anyway. Pyproject has long since become the standard for many Python projects, so we prefer this over `myst.yml`. So configuration would be done in 
`pyproject.toml`
instead.

Is this a thing that is valuable to discuss? Is it maybe already implemented, because we could imagine it is not, thinking of the importance of the toml format to python in the format.

**Comment by chrisjsewell** [comment]
Heya, I would link to https://github.com/sphinx-doc/sphinx/issues/9040, as ideally this would be something that could be done at the "sphinx level"

**Comment by pascal456** [comment]
thanks for the quick answer @chrisjsewell !
So I just started to look into myst and I was not aware of that. Do I understand correctly that under the hood, it is the Sphinx package whit what the documents (websites in my case) are being built?
