### ISSUE TITLE
Allow for links links and titles in block quote attributions

### ISSUE THREAD

**Issue by hynek** [executablebooks/MyST-Parser#830]
I would like to use `attrs_block` attributions for my block quotes but it seems like I can't have a title and a link in there. If I use a Markdown link, it's used verbatim, if I use an HTML link, the attrs line is rendered verbatim.

Ideally it would be a separate attribute:

```markdown
{attribution="Hyrum Wright", attribution_title="Hyrum's Law" attribution_link="https://www.hyrumslaw.com"}
> With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody.
```

would give me:

```html
<blockquote cite="https://www.hyrumslaw.com">
  <p>With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody.</p>

  <cite>— Hyrum Wright, <a href="https://www.hyrumslaw.com">Hyrum’s Law</a></cite>
</blockquote>
```

**Comment by chrisjsewell** [comment]
Heya, see #831, I agree that the attribution should be parsed as MyST

> would give me ...

I'm not sure about acheiving this though;
I agree that this looks to be a better HTML representation (like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote),
but I think it would require changes to the upstream HTML renderer; https://github.com/live-clones/docutils/blob/master/docutils/docutils/writers/_html_base.py

**Comment by hynek** [comment]
BTW I'm sorry if I've accidentally circumvented some kind of community process as the message of the bot insinuates. I just clicked "new issue" in the docs and search the issues for "attribution" (and found nothing).

**Comment by chrisjsewell** [comment]
> as the message of the bot insinuates

Oh no, this just gets fired for every first-time contributor 😄

**Comment by hynek** [comment]
Yeah I didn't feel attacked specifically, I'm just seeing mentions of issue templates (I had none) etc. :)

**Comment by chrisjsewell** [comment]
@hynek would #831 be sufficient for you at this time?
 I could potentially add something like a `cite` attribute that is "stored" on the `block_quote` node:

```
{attribution="Hyrum Wright", cite="https://www.hyrumslaw.com/"}
> With a sufficient number
```

But, as I mention above, I don't think this would currently propagate to the actual output HTML

**Comment by hynek** [comment]
Would #831 mean I can do:

```md
{attribution="Hyrum Wright, [Hyrum’s Law](https://www.hyrumslaw.com>)"}
> With a sufficient number
```

And get:

```html
<blockquote>
  <p>With a sufficient number…</p>

  <cite>— Hyrum Wright, <a href="https://www.hyrumslaw.com">Hyrum’s Law</a></cite>
</blockquote>
```

?

I don't care that much about the cite attribute because I don't think anyone is actually using it? I primarily want to be able to have richer citations in the cite tag. :)

**Comment by chrisjsewell** [comment]
> Would https://github.com/executablebooks/MyST-Parser/pull/831 mean I can do

yep 👍 see the updated example in https://myst-parser--831.org.readthedocs.build/en/831/syntax/optional.html#attributes

**Comment by hynek** [comment]
Well, perfect!
