### ISSUE TITLE
Create a new release to capture the docutils warnings fixes

### ISSUE THREAD

**Issue by willingc** [executablebooks/MyST-Parser#870]
### Describe the feature you'd like to request

@choldgraf When you get a chance, please cut a new release. We are hoping to get the docutils warning fixes in so we can avoid pinning to a SHA. Thanks a bunch!

**Comment by chrisjsewell** [comment]
Heya, I've got a few things to check this week, then I'll release a new version 👍

**Comment by chrisjsewell** [comment]
all done
