### ISSUE TITLE
Line braks doesn't work.

### ISSUE THREAD

**Issue by sargis2000** [executablebooks/MyST-Parser#877]
### What version of `myst-parser` are you using?

2.0.0

### What version dependencies are you using?

Sphinx==7.2.6

### What operating system are you using?

Linux

### Describe the Bug

The line line-break  doesn't work in  confluence.
Pls see this tickets.
[opened Spinx bug](https://github.com/sphinx-doc/sphinx/issues/11999 )
[opened confluence builder](https://github.com/sphinx-contrib/confluencebuilder/issues/879)

**Comment by chrisjsewell** [comment]
I believe https://github.com/executablebooks/MyST-Parser/pull/900 closes this 😄 see updated [myst-parser.readthedocs.io/en/latest/syntax/typography.html#line-breaks](https://myst-parser.readthedocs.io/en/latest/syntax/typography.html#line-breaks)

I'll close this as fixed, but feel free to re-open or open a new issue, if there is anything else
