### ISSUE TITLE
Support sphinx 7.3 - use default config value types

### ISSUE THREAD

**Issue by arwedus** [executablebooks/MyST-Parser#889]
https://github.com/executablebooks/MyST-Parser/blob/978e845543b5bcb7af0ff89cac9f798cb8c16ab3/myst_parser/sphinx_ext/main.py#L56

for sphinx 7.3 support, this should be rewritten to:

```py
    for name, default, field in MdParserConfig().as_triple():
        if "sphinx" not in field.metadata.get("omit", []):
            app.add_config_value(f"myst_{name}", default, "env")
```

-> The allowed type is then the one from the default value, which seems to always be set correctly.

See also:

https://github.com/sphinx-doc/sphinx/pull/11746#issuecomment-2016605370

**Comment by chrisjsewell** [comment]
> The allowed type is then the one from the default value, which seems to always be set correctly.

Hi @arwedus, it does not I'm afraid,
`types=Any` was added to fix https://github.com/executablebooks/MyST-Parser/issues/558

**Comment by chrisjsewell** [comment]
this is now fixed in sphinx
