### ISSUE TITLE
For v3.0.1: If the last directive option has an empty value then it is omitted

### ISSUE THREAD

**Issue by hroemer** [executablebooks/MyST-Parser#923]
### What version of `myst-parser` are you using?

3.0.0

### What version dependencies are you using?

sphinx=7.3.7
docutils=0.20.1

### What operating system are you using?

Linux

### Describe the Bug

The glob patterns defined in a toctree directive do not work with `3.0.0` anymore.

### To Reproduce

````markdown
```{toctree}
---
maxdepth: 2
caption: Contents
glob:
---
path*/index
pages/**
*/index
```
````

**Comment by chrisjsewell** [comment]
Heya, gotta look into exactly what is going on here, but if you change the order of the option, I think it will work, e.g.

````
```{toctree}
---
maxdepth: 2
glob:
caption: Contents
---
path*/index
pages/**
*/index
```
````

let me know?

**Comment by chrisjsewell** [comment]
> I will have to grep through my multiple toctrees split over hundreds of files, now 😉.

well, if its not urgent, then I would hope to have a fix in perhaps the next few days 😅
