### ISSUE TITLE
Substitution in Block doesn't seem to work in Live Preview

### ISSUE THREAD

**Issue by salomon-chung** [executablebooks/MyST-Parser#935]
### What version of `myst-parser` are you using?

3.0.0

### What version dependencies are you using?

pyodide-0.21.3

### What operating system are you using?

Linux

### Describe the Bug

Running the following code gives errors in https://myst-parser.readthedocs.io/en/latest/live-preview.html:
```
---
myst:
    substitutions:
        key: "I'm a **substitution**"
---
# Test

## Text

{{ key }}

## Code Block

{{
    "```\n" + key + "\n```"
}}

## Code Block + Environment

{{
    "```\n" + env.docname + "\n```"
}}
```
![live-preview](https://github.com/executablebooks/MyST-Parser/assets/100271711/f656b5e3-50e7-4303-81d0-348f1983e211)

### Expected Behavior

Substitution in block seems to work in this MWE:
- https://gitlab.com/uranie-cea/documentation/substitution-in-block/-/blob/main/test.md?ref_type=heads&plain=1
- https://substitution-in-block-uranie-cea-documentation-de220cba8224ddaf.gitlab.io/test.html

![pages](https://github.com/executablebooks/MyST-Parser/assets/100271711/cbde4841-8192-4c66-9c94-6a24451a6991)

Is it the expected behaviour?

### To Reproduce

1. Go to https://myst-parser.readthedocs.io/en/latest/live-preview.html
2. In Configuration (YAML), define:
    ```
   myst_enable_extensions:
   - substitution
    ```
3. Copy the previous code.

**Comment by chrisjsewell** [comment]
Heya, as it mentions on the preview page, this is running the docutils parser, not the sphinx one, and so there is no `env`  (i.e. `BuildEnvironment`) which a sphinx only thing
