### ISSUE TITLE
Support Sphinx v8

### ISSUE THREAD

**Issue by BoboTiG** [executablebooks/MyST-Parser#950]
### Describe the feature you'd like to request

Sphinx 8.0.2 is available to public (https://www.sphinx-doc.org/en/master/changes.html). Current requirements are pinned so that it's not possible to do the upgrade as of now: https://github.com/executablebooks/MyST-Parser/blob/d3d7fbb6a4fd2ecd12c7a29d7de902a869897eb9/pyproject.toml#L43

Example of `pip` output:

```
The conflict is caused by:
    The user requested sphinx==8.0.2
    myst-parser 3.0.1 depends on sphinx<8 and >=6
```

### Describe the solution you'd like

Support Sphinx v8.

**Comment by BoboTiG** [comment]
It is worth noting that they droppee Python 3.9 support.

**Comment by chrisjsewell** [comment]
Heya, yep aim to do it in the next few weeks
